#!/usr/bin/env Rscript
# moral-economy — MECHANICAL CHECKS ON THE RSP MANUSCRIPT.
#
# RSP enforces two hard limits and one formatting rule that are cheap to violate and expensive to
# discover at desk-reject: the abstract is <= 1 000 CHARACTERS, the whole manuscript <= 50 000
# characters including references and appendices, and numbers use a decimal comma with a space
# thousands separator. PROPOSAL_v5 E3 records that an earlier abstract was ASSERTED at 986 characters
# and actually measured 1 009. So this measures rather than asserts.
#
# It also closes the drift risk that comes with tables: every table in the manuscript is generated by
# 26_rsp_tables.R, so the fragments must still appear byte-for-byte, and every number quoted in the
# prose must still match the scalar the same script derived from output/.
#
#   Rscript studies/moral-economy/25_paper_checks.R
suppressPackageStartupMessages({ library(here) })
source(here::here("studies/moral-economy/sem_lib.R"))
source(here::here("studies/moral-economy/rsp_labels.R"))

PAPER  <- here::here("studies/moral-economy/PAPER_RSP_v1.md")
TABDIR <- file.path(ME_OUT, "tables")
FIGDIR <- file.path(ME_OUT, "figures")
txt <- readLines(PAPER, encoding = "UTF-8", warn = FALSE)
raw <- paste(txt, collapse = "\n")
res <- logical(0)
ok  <- function(cond, label, detail = "") {
  cat(sprintf("[%s] %-46s %s\n", if (isTRUE(cond)) " OK " else "FAIL", label, detail))
  res <<- c(res, isTRUE(cond)); invisible(cond)
}

cat("=== RSP manuscript checks ===\n\n--- length ---\n")

## ---- abstract length -------------------------------------------------------------------------
a0 <- grep("^## Abstract \\(English\\)", txt); a1 <- grep("^\\*\\*Keywords", txt)[1]
abs_txt <- gsub("\\s+", " ", trimws(paste(trimws(txt[(a0 + 1):(a1 - 1)]), collapse = " ")))
n <- nchar(abs_txt)
ok(n <= 1000, "English abstract <= 1 000 characters", sprintf("%d characters, %d to spare", n, 1000 - n))

## ---- manuscript length -----------------------------------------------------------------------
b0 <- grep("^## 1\\. ", txt); b1 <- grep("^## Appendix A", txt)
body  <- txt[b0:(b1 - 1)]
words <- length(unlist(strsplit(paste(body, collapse = " "), "\\s+")))
# Table cells are padded to a common width so the manuscript is readable as plain text. That padding
# is not in the exported Word table, so it is collapsed before measuring against the journal's cap.
flat  <- ifelse(grepl("^\\|", txt), gsub(" +", " ", txt), txt)
total <- nchar(paste(flat, collapse = "\n"))
cat(sprintf("      body (sections 1-9 + references + declarations): %s words, %s characters\n",
            format(words, big.mark = " "), format(nchar(paste(body, collapse = " ")), big.mark = " ")))
ok(total < 50000, "whole manuscript < 50 000 characters",
   sprintf("%s characters incl. appendices; %s left for the Croatian abstract",
           format(total, big.mark = " "), format(50000 - total, big.mark = " ")))

## ---- number format ---------------------------------------------------------------------------
# A decimal point inside a number is the house-rule violation to catch. Version strings, file names,
# section numbers and the +-220 window are not decimals, so they are excluded rather than reported
# as 40 false alarms.
prose <- body[!grepl("^\\s*[|`!]|^\\s*&|^```|\\.md|\\.R\\b|\\.csv|\\.rds|\\.png", body)]
hits <- unlist(regmatches(prose, gregexpr("[0-9]+\\.[0-9]+", prose)))
hits <- hits[!grepl("^(1|2|3|4|5|6|7|8|9)\\.[0-9]$", hits)]   # section cross-references
ok(length(hits) == 0, "decimal comma throughout the prose",
   if (length(hits)) paste("offenders:", paste(unique(hits), collapse = ", ")) else "clean")

## ---- no drafting scaffolding left in the manuscript --------------------------------------------
forbidden <- c("DRAFTING STATUS", "✅", "TODO", "Still to resolve", "not yet verified",
               "Not yet verified", "@@TAB", "to be drafted", "Draft v1")
left <- forbidden[vapply(forbidden, function(f) grepl(f, raw, fixed = TRUE), logical(1))]
ok(length(left) == 0, "no drafting scaffolding in the text",
   if (length(left)) paste("found:", paste(left, collapse = ", ")) else "clean")

## ---- tables and figures ------------------------------------------------------------------------
cat("\n--- tables and figures ---\n")
frags <- list.files(TABDIR, pattern = "^tab.*\\.md$", full.names = TRUE)
ok(length(frags) == 7, "seven generated table fragments exist", sprintf("%d found", length(frags)))
for (f in frags) {
  frag <- paste(readLines(f, encoding = "UTF-8", warn = FALSE), collapse = "\n")
  ok(grepl(trimws(frag), raw, fixed = TRUE), paste0("table intact: ", basename(f)),
     "matches the generated fragment")
}
figs <- c("rsp_fig1_gradient.png", "rsp_fig2_era.png", "rsp_fig3_boundary.png",
          "rsp_fig4_vocabulary.png")
for (f in figs) {
  ok(file.exists(file.path(FIGDIR, f)) && grepl(f, raw, fixed = TRUE),
     paste0("figure present and referenced: ", f), "")
}

## ---- re-derive the headline numbers from the output files --------------------------------------
cat("\n--- numeric claims re-derived from output/ ---\n")
chk <- function(label, claimed, actual, tol = 0.05) {
  ok(abs(claimed - actual) <= tol, label,
     sprintf("paper %s / file %s", format(claimed), format(round(actual, 3))))
}
p  <- read.csv(file.path(ME_OUT, "r1_numerator_precision.csv"), fileEncoding = "UTF-8")
chk("R1 numerator precision (%)", 83.3, p$rate[p$axis == "r1_genuine"])
chk("R1 detector non-error (%)", 99.3, p$rate[p$axis == "r1_not_false"])
chk("R2 economic-term validity (%)", 76.0, p$rate[p$axis == "r2_econ_true"])

g  <- read.csv(file.path(ME_OUT, "cst_gradient_adjusted.csv"), fileEncoding = "UTF-8")
gc <- g[g$code == "ax1_link_genuine", ]
chk("corrected climate rate (%)", 14.80, gc$adj_rate[gc$domain == "green_energy"])
chk("raw climate rate (%)", 7.15, gc$raw_rate[gc$domain == "green_energy"])
v <- sort(gc$adj_rate, decreasing = TRUE)
chk("corrected ratio to runner-up", 1.91, v[1] / v[2], tol = 0.02)

pr <- read.csv(file.path(ME_OUT, "r4_linkage_precision.csv"), fileEncoding = "UTF-8")
pc <- pr[pr$code == "ax1_link_genuine", ]
den <- gc$linked[match(pc$domain, gc$domain)]
chk("layer-weighted linkage precision (%)", 39.5, sum(pc$precision * den) / sum(den))
chk("min domain linkage precision (%)", 21.7, min(pc$precision))
chk("max domain linkage precision (%)", 63.3, max(pc$precision))
chk("corrected headline rate (%)", 3.73,
    100 * sum(gc$doctrinal) / (sum(gc$linked) * sum(pc$precision * den) / sum(den) / 100))

d <- read.csv(file.path(ME_OUT, "cst_robustness_detail.csv"), fileEncoding = "UTF-8")
chk("confessional climate rate (%)", 22.31,
    d$rate[d$variant == "confessional_only" & d$domain == "green_energy"])
chk("secular_max climate rate (%)", 5.16,
    d$rate[d$variant == "secular_max" & d$domain == "green_energy"])

## ---- every derived scalar still appears in the manuscript as printed ---------------------------
# 26_rsp_tables.R writes each quantity the article quotes; here we check the printed form is still
# somewhere in the text. A number that changed upstream disappears from the manuscript and fails.
cat("\n--- derived scalars still present in the text ---\n")
dv <- read.csv(file.path(TABDIR, "rsp_derived.csv"), fileEncoding = "UTF-8")
val <- function(nm) dv$value[match(nm, dv$name)]
want <- list(
  c("linked_posts", "int"), c("linked_pairs", "int"), c("core_posts", "int"), c("core_pairs", "int"),
  c("adjacency_cost", "int"), c("poverty_linked", "int"), c("term_occurrences", "int"),
  c("gold_links_n", "int"), c("opcija_corpus", "int"), c("socnauk_core", "int"),
  c("raw_rate_pairs", "2"), c("corrected_headline", "2"), c("corrected_headline_strict", "2"),
  c("tier2_ceiling", "2"), c("climate_raw", "2"), c("climate_adj", "2"), c("adj_ratio", "2"),
  c("raw_ratio", "2"), c("euro_hi", "2"), c("opcija_pct", "2"),
  c("conf_climate", "2"), c("conf_next", "2"), c("conf_ratio", "2"),
  c("secmin_climate", "2"), c("secmin_next", "2"), c("secmin_ratio", "2"),
  c("secmax_climate", "2"), c("secmax_next", "2"), c("secmax_ratio", "2"),
  c("w_gen", "1"), c("w_str", "1"), c("chisq", "1"), c("prec_min", "1"), c("prec_max", "1"),
  c("rank_cor", "2"), c("conf_share_linked", "1"), c("conf_share_doctrinal", "1"),
  c("conf_share_linked_labelled", "1"), c("conf_share_doctrinal_labelled", "1"),
  c("classical_green", "1"), c("classical_business", "1"), c("classical_housing", "1"),
  c("classical_wages", "1"), c("francis_green", "1"),
  c("poverty_share_pairs", "1"), c("poverty_charity", "1"), c("poverty_justice", "1"), c("poverty_remainder", "1"),
  c("green_justice", "1"))
miss <- character(0)
for (w in want) {
  s <- if (w[2] == "int") rsp_int(val(w[1])) else rsp_num(val(w[1]), as.integer(w[2]))
  if (!grepl(s, raw, fixed = TRUE)) miss <- c(miss, paste0(w[1], " (", s, ")"))
}
ok(length(miss) == 0, sprintf("all %d derived scalars printed in the text", length(want)),
   if (length(miss)) paste("missing:", paste(miss, collapse = "; ")) else "no drift")

cat(sprintf("\n%d of %d checks pass.\n", sum(res), length(res)))
if (!all(res)) stop("The manuscript does not reconcile with output/.", call. = FALSE)
