#!/usr/bin/env Rscript
# moral-economy — MECHANICAL CHECKS ON THE RSP MANUSCRIPT.
#
# These checks enforce the target journal's length and formatting constraints on the public manuscript.
# They do not certify double-blind anonymisation; an anonymous submission copy remains a separate export.
# The abstract is <= 1 000 CHARACTERS, the whole manuscript <= 50 000
# characters including references and appendices, and numbers use a decimal comma with a space
# thousands separator. PROPOSAL_v5 E3 records that an earlier abstract was ASSERTED at 986 characters
# and actually measured 1 009. So this measures rather than asserts.
#
# It also closes the drift risk that comes with tables: every table in the manuscript is generated by
# 26_rsp_tables.R, so the fragments must still appear byte-for-byte, and every number quoted in the
# prose must still match the scalar the same script derived from output/.
#
# The manuscript exists in two versions. v1 is the plain-language draft; v2 is the academic-structure
# rewrite. Both are built from the SAME table fragments and the SAME derived scalars, so every check
# below is identical and only the target file changes.
#
#   Rscript studies/moral-economy/25_paper_checks.R          # v1
#   Rscript studies/moral-economy/25_paper_checks.R --v2     # v2
suppressPackageStartupMessages({ library(here) })
source(here::here("studies/moral-economy/sem_lib.R"))
source(here::here("studies/moral-economy/rsp_labels.R"))
source(here::here("studies/moral-economy/rsp_input.R"))
source(here::here("studies/moral-economy/cst_core.R"))

VERSION <- if ("--v2" %in% commandArgs(trailingOnly = TRUE)) "v2" else "v1"
PAPER  <- here::here(sprintf("studies/moral-economy/PAPER_RSP_%s.md", VERSION))
if (!file.exists(PAPER)) stop("No such manuscript: ", PAPER, call. = FALSE)
TABDIR <- file.path(ME_OUT, "tables")
FIGDIR <- file.path(ME_OUT, "figures")
txt <- readLines(PAPER, encoding = "UTF-8", warn = FALSE)
raw <- paste(txt, collapse = "\n")
res <- logical(0)
ok  <- function(cond, label, detail = "") {
  cat(sprintf("[%s] %-46s %s\n", if (isTRUE(cond)) " OK " else "FAIL", label, detail))
  res <<- c(res, isTRUE(cond)); invisible(cond)
}

## ---- sealed-run identity -----------------------------------------------------------------------
FINAL_MANIFEST <- file.path(ME_OUT, "rsp_final_run_manifest.json")
ok(file.exists(FINAL_MANIFEST), "final run manifest exists", basename(FINAL_MANIFEST))
if (!file.exists(FINAL_MANIFEST)) stop("Run 36_rsp_final_run_manifest.R after syncing tables.", call. = FALSE)
fm <- jsonlite::fromJSON(FINAL_MANIFEST, simplifyVector = FALSE)
sealed_groups <- c("inputs", "restricted_audit_inputs", "public_analysis_outputs",
                   "generated_tables", "generated_figures", "manuscripts_and_pipeline",
                   "analysis_sources")
hash_fail <- character(0); n_sealed <- 0L
for (grp in sealed_groups) {
  rr <- fm[[grp]]
  if (!length(rr)) { hash_fail <- c(hash_fail, paste0(grp, ": empty")); next }
  for (rec in rr) {
    n_sealed <- n_sealed + 1L
    p <- here::here(rec$path)
    if (!file.exists(p)) hash_fail <- c(hash_fail, paste0(rec$path, " (missing)"))
    else if (!identical(digikat_hash_file(p), as.character(rec$sha256)))
      hash_fail <- c(hash_fail, paste0(rec$path, " (hash drift)"))
  }
}
ok(!length(hash_fail), "all final-run files match sealed hashes",
   if (length(hash_fail)) paste(hash_fail, collapse = "; ") else paste(n_sealed, "files"))
failed_axes <- unlist(fm$gates$stability_failed_axes, use.names = FALSE)
ok(identical(fm$status, "complete_with_reported_failed_measurement_gate") &&
     identical(fm$gates$same_domain_core_reconciles, TRUE) &&
     identical(fm$gates$stability_passed, FALSE) &&
     identical(as.character(failed_axes), "r2_econ_true"),
   "sealed gates retain the reported R2 failure", "r2_econ_true is the sole failed stability axis")

cat(sprintf("=== RSP manuscript checks (%s) ===\n\n--- length ---\n", basename(PAPER)))

## ---- abstract length -------------------------------------------------------------------------
a0 <- grep("^## Abstract \\(English\\)", txt); a1 <- grep("^\\*\\*Keywords", txt)[1]
abs_txt <- gsub("\\s+", " ", trimws(paste(trimws(txt[(a0 + 1):(a1 - 1)]), collapse = " ")))
n <- nchar(abs_txt)
ok(n <= 1000, "English abstract <= 1 000 characters", sprintf("%d characters, %d to spare", n, 1000 - n))

h0 <- grep("^## Sažetak \\(hrvatski\\)", txt); h1 <- grep("^\\*\\*Ključne riječi", txt)[1]
hr_txt <- gsub("\\s+", " ", trimws(paste(trimws(txt[(h0 + 1):(h1 - 1)]), collapse = " ")))
nh <- nchar(hr_txt)
ok(nh <= 1000, "Croatian abstract <= 1 000 characters", sprintf("%d characters, %d to spare", nh, 1000 - nh))

## ---- manuscript length -----------------------------------------------------------------------
b0 <- grep("^## 1\\. ", txt); b1 <- grep("^## Appendix A", txt)
body  <- txt[b0:(b1 - 1)]
words <- length(unlist(strsplit(paste(body, collapse = " "), "\\s+")))
# Table cells are padded to a common width so the manuscript is readable as plain text. That padding
# is not in the exported Word table, so it is collapsed before measuring against the journal's cap.
flat  <- ifelse(grepl("^\\|", txt), gsub(" +", " ", txt), txt)
total <- nchar(paste(flat, collapse = "\n"))
cat(sprintf("      body (sections 1-9 + references + declarations): %s words, %s characters\n",
            format(words, big.mark = " "), format(nchar(paste(body, collapse = " ")), big.mark = " ")))
ok(total < 50000, "whole manuscript < 50 000 characters",
   sprintf("%s characters incl. appendices; %s left for the Croatian abstract",
           format(total, big.mark = " "), format(50000 - total, big.mark = " ")))

## ---- number format ---------------------------------------------------------------------------
# A decimal point inside a number is the house-rule violation to catch. Version strings, file names,
# section numbers and the +-220 window are not decimals, so they are excluded rather than reported
# as 40 false alarms.
prose <- body[!grepl("^\\s*[|`!]|^\\s*&|^```|\\.md|\\.R\\b|\\.csv|\\.rds|\\.png", body)]
prose <- gsub("https?://[^[:space:]]+", "", prose)
hits <- unlist(regmatches(prose, gregexpr("[0-9]+\\.[0-9]+", prose)))
hits <- hits[!grepl("^(1|2|3|4|5|6|7|8|9)\\.[0-9]$", hits)]   # section cross-references
ok(length(hits) == 0, "decimal comma throughout the prose",
   if (length(hits)) paste("offenders:", paste(unique(hits), collapse = ", ")) else "clean")

## ---- no drafting scaffolding left in the manuscript --------------------------------------------
forbidden <- c("DRAFTING STATUS", "✅", "TODO", "Still to resolve", "not yet verified",
               "Not yet verified", "@@TAB", "to be drafted", "Draft v1")
left <- forbidden[vapply(forbidden, function(f) grepl(f, raw, fixed = TRUE), logical(1))]
ok(length(left) == 0, "no drafting scaffolding in the text",
   if (length(left)) paste("found:", paste(left, collapse = ", ")) else "clean")

## ---- tables and figures ------------------------------------------------------------------------
cat("\n--- tables and figures ---\n")
frags <- list.files(TABDIR, pattern = "^tab.*\\.md$", full.names = TRUE)
ok(length(frags) == 7, "seven generated table fragments exist", sprintf("%d found", length(frags)))
for (f in frags) {
  frag <- paste(readLines(f, encoding = "UTF-8", warn = FALSE), collapse = "\n")
  ok(grepl(trimws(frag), raw, fixed = TRUE), paste0("table intact: ", basename(f)),
     "matches the generated fragment")
}
figs <- c("rsp_fig1_gradient.png", "rsp_fig2_era.png", "rsp_fig3_boundary.png",
          "rsp_fig4_lexicon_sensitivity.png")
for (f in figs) {
  refs <- lengths(regmatches(raw, gregexpr(f, raw, fixed = TRUE)))
  ok(file.exists(file.path(FIGDIR, f)) && refs == 1L,
     paste0("figure present and referenced once: ", f), paste(refs, "reference(s)"))
}
# A figure's title and source note are typeset on the page, not drawn into the PNG, so they are
# generated text and drift the same way a table does. 24_rsp_figures.R writes them; they must still
# appear here exactly as generated.
figfrags <- list.files(FIGDIR, pattern = "^fig[0-9].*\\.md$", full.names = TRUE)
ok(length(figfrags) == 4, "four generated figure fragments exist", sprintf("%d found", length(figfrags)))
for (f in figfrags) {
  frag <- paste(readLines(f, encoding = "UTF-8", warn = FALSE), collapse = "\n")
  ok(grepl(trimws(frag), raw, fixed = TRUE), paste0("figure caption intact: ", basename(f)),
     "matches the generated fragment")
}
ok(!grepl("![Figure ", raw, fixed = TRUE),
   "no figure carries its title inside the image", "captions are typeset on the page")
ok(!grepl("rsp_fig4_vocabulary.png", raw, fixed = TRUE),
   "obsolete vocabulary figure is not referenced", "clean")

## ---- re-derive the headline numbers from the output files --------------------------------------
cat("\n--- numeric claims re-derived from output/ ---\n")
p <- read.csv(file.path(ME_OUT, "r1_numerator_precision.csv"), fileEncoding = "UTF-8")
ok(setequal(p$axis, c("r1_genuine", "r1_not_false", "r2_econ_true", "r1_and_r2")) &&
     all(p$n == 150) && all(p$rate >= 0 & p$rate <= 100),
   "R1/R2 output is complete and bounded", sprintf("%d rows; n=%s", nrow(p), paste(unique(p$n), collapse = ",")))

g <- read.csv(file.path(ME_OUT, "cst_gradient_adjusted.csv"), fileEncoding = "UTF-8")
gc <- g[g$code == "ax1_link_genuine", ]
pr <- read.csv(file.path(ME_OUT, "r4_linkage_precision.csv"), fileEncoding = "UTF-8")
pc <- pr[pr$code == "ax1_link_genuine", ]
pm <- pc$precision[match(gc$domain, pc$domain)]
raw_expected <- 100 * gc$doctrinal / gc$linked
adj_expected <- 100 * gc$doctrinal / (gc$linked * pm / 100)
expected_domains <- names(ME_ECON)
complete_gradient <- nrow(gc) == length(expected_domains) && !anyDuplicated(gc$domain) &&
  setequal(gc$domain, expected_domains) && !anyNA(pm) &&
  all(is.finite(c(gc$linked, gc$doctrinal, gc$raw_rate, gc$precision, gc$adj_rate, pm)))
ok(complete_gradient && max(abs(gc$raw_rate - raw_expected)) < 1e-8,
   "raw gradient re-derives from official pair counts", sprintf("%d domains", nrow(gc)))
ok(complete_gradient && max(abs(gc$precision - pm)) < 1e-8 &&
     max(abs(gc$adj_rate - adj_expected)) < 1e-8,
   "adjusted gradient re-derives from R4 precision", "all domains reconcile")

d <- read.csv(file.path(ME_OUT, "cst_robustness_detail.csv"), fileEncoding = "UTF-8")
base <- d[d$variant == "baseline", ]
base_rate <- base$rate[match(gc$domain, base$domain)]
ok(nrow(base) == length(expected_domains) && !anyNA(base_rate) && all(is.finite(base_rate)) &&
     max(abs(gc$raw_rate - base_rate)) < 0.0011,
   "gradient baseline matches robustness output", "rounded CSVs reconcile")

core_now <- cst_build_core(verbose = FALSE)
core_pairs_now <- cst_core_pairs(core_now)
era_now <- read.csv(file.path(ME_OUT, "cst_core_domain_era.csv"), fileEncoding = "UTF-8")
ok(sum(era_now$Freq) == nrow(core_pairs_now) && sum(gc$doctrinal) == nrow(core_pairs_now),
   "pair-specific era and gradient totals equal core pairs",
   sprintf("%d = %d = %d", sum(era_now$Freq), sum(gc$doctrinal), nrow(core_pairs_now)))

im <- rsp_read_input_manifest()
current_corpus <- digikat_read_corpus_manifest()$corpus
ok(as.integer(im$database$rows) == as.integer(current_corpus$rows) &&
     identical(as.character(im$database$sha256), as.character(current_corpus$sha256)),
   "paper run is pinned to the current official corpus",
   paste(im$database$rows, substr(im$database$sha256, 1, 12)))
old_markers <- c("710 307", "108 966", "132 519", "1 198 teaching posts",
                 "1 111", "1 797", "82,9%", "14,82%", "4,27%", "6,33%")
stale <- old_markers[vapply(old_markers, function(x) grepl(x, raw, fixed = TRUE), logical(1))]
ok(length(stale) == 0, "no legacy-accumulator headline survives",
   if (length(stale)) paste("found:", paste(stale, collapse = ", ")) else "clean")

## ---- every derived scalar still appears in the manuscript as printed ---------------------------
# 26_rsp_tables.R writes each quantity the article quotes; here we check the printed form is still
# somewhere in the text. A number that changed upstream disappears from the manuscript and fails.
cat("\n--- derived scalars still present in the text ---\n")
dv <- read.csv(file.path(TABDIR, "rsp_derived.csv"), fileEncoding = "UTF-8")
val <- function(nm) dv$value[match(nm, dv$name)]
want <- list(
  c("corpus_n", "int"),
  c("linked_posts", "int"), c("linked_pairs", "int"), c("core_posts", "int"), c("core_pairs", "int"),
  c("inclusive_frame_posts", "int"), c("inclusive_frame_pairs", "int"),
  c("inclusive_core_posts", "int"), c("inclusive_core_pairs", "int"),
  c("raw_rate_pairs", "2"), c("corrected_headline", "2"), c("corrected_headline_strict", "2"),
  c("raw_rate_posts", "2"), c("post_invocation_sensitivity", "2"), c("post_joint_sensitivity", "2"),
  c("r1_genuine", "1"), c("r1_joint", "1"),
  c("w_gen", "1"), c("w_str", "1"),
  c("climate_raw", "2"), c("climate_adj", "2"), c("strict_macro", "2"),
  c("no_laudato_climate_raw", "2"), c("no_laudato_top_raw", "2"),
  c("no_ecology_climate_raw", "2"), c("no_ecology_top_raw", "2"),
  c("no_laudato_climate_denom", "2"), c("no_laudato_top_denom", "2"),
  c("no_ecology_climate_denom", "2"), c("no_ecology_top_denom", "2"),
  c("conf_climate", "2"), c("conf_next", "2"), c("conf_ratio", "2"),
  c("secmin_climate", "2"), c("secmin_next", "2"), c("secmin_ratio", "2"),
  c("secmax_climate", "2"), c("secmax_next", "2"), c("secmax_ratio", "2"),
  c("stability_agreement_min", "1"), c("stability_agreement_max", "1"),
  c("stability_kappa_min", "3"), c("stability_kappa_max", "3"),
  c("variants_first", "int"), c("variants_n", "int"), c("variants_disjoint", "int"),
  c("classical_green", "1"), c("classical_business", "1"),
  c("classical_wages", "1"), c("francis_green", "1"),
  c("poverty_reg_n", "int"), c("poverty_charity", "1"), c("poverty_justice", "1"),
  c("poverty_remainder", "1"), c("green_justice", "1"),
  c("gold_links_n", "int"), c("gold_display_n", "int"), c("gold_database_n", "int"),
  c("gold_linked_n", "int"), c("term_occurrences", "int"), c("socnauk_core", "int"),
  c("opcija_corpus", "int"))
miss <- character(0)
for (w in want) {
  s <- if (w[2] == "int") rsp_int(val(w[1])) else rsp_num(val(w[1]), as.integer(w[2]))
  if (!grepl(s, raw, fixed = TRUE)) miss <- c(miss, paste0(w[1], " (", s, ")"))
}
ok(length(miss) == 0, sprintf("all %d derived scalars printed in the text", length(want)),
   if (length(miss)) paste("missing:", paste(miss, collapse = "; ")) else "no drift")

cat(sprintf("\n%d of %d checks pass.\n", sum(res), length(res)))
if (!all(res)) stop("The manuscript does not reconcile with output/.", call. = FALSE)
