---
title: " "
---
<br>
<br>
<br>
<br>

      
### 游닄 Resursi i korisni linkovi

Ovdje smo pripremili kuriranu listu resursa koja 캖e vam pomo캖i da dublje zaronite u svijet ra캜unalnih dru코tvenih znanosti, analize podataka i alata koje koristimo na ovom projektu.

---

#### 游눹 Uvod u alate i programske jezike

Ovi resursi idealni su za sve koji 쬰le nau캜iti ili usavr코iti svoje vje코tine u programskim jezicima R i Python, koji su temelj na코eg analiti캜kog rada.

**Za korisnike R-a:**

*   **RStudio: Finding Your Way To R** - *Slu쬭eni vodi캜 za po캜etnike koji pokriva osnove rada u RStudio okru쬰nju.* [Link](https://education.rstudio.com/learn/)
*   **R for Data Science** - *"Biblija" za svakoga tko se bavi analizom podataka u R-u. Autori su Hadley Wickham i Garrett Grolemund.* [Link](https://r4ds.had.co.nz/)
*   **Text Mining with R** - *Odli캜na knjiga za uvod u analizu teksta, s naglaskom na `tidy` principe. Autorice su Julia Silge i David Robinson.* [Link](https://www.tidytextmining.com/)
*   **CRAN Task View: Social Sciences** - *Kurirana lista R paketa specifi캜no namijenjenih za primjenu u dru코tvenim znanostima.* [Link](https://cran.r-project.org/web/views/SocialSciences.html)
*   **R-bloggers** - *Agregator najboljih blogova o R-u, svakodnevno donosi nove tutorijale i studije slu캜aja.* [Link](https://www.r-bloggers.com/)

**Za korisnike Pythona:**

*   **The Python Tutorial** - *Slu쬭ena dokumentacija i najbolja polazna to캜ka za u캜enje osnova Pythona.* [Link](https://docs.python.org/3/tutorial/)
*   **spaCy 101** - *Moderna i brza biblioteka za obradu prirodnog jezika (NLP). Njihov te캜aj je odli캜an za po캜etnike.* [Link](https://course.spacy.io/)
*   **Real Python** - *Visokokvalitetni tutorijali za sve razine znanja, od osnova do naprednih tema.* [Link](https://realpython.com/)

---

#### 游눠 Temeljna literatura i koncepti

Knjige i znanstveni radovi koji oblikuju podru캜je kojim se bavimo.

**Ra캜unalne dru코tvene znanosti:**

*   **Bit by Bit: Social Research in the Digital Age** - *Klju캜na knjiga Matthewa Salganika koja obja코njava kako digitalno doba transformira dru코tvena istra쬴vanja.* [Link](https://www.bitbybitbook.com/)
*   **Computational Social Science: A Manifesto** - *Seminalni rad (Lazer i sur.) koji je definirao polje i njegove glavne izazove i prilike.* [Link](https://www.science.org/doi/10.1126/science.1167742)

**Analiza teksta kao podatka:**

*   **Text as Data: A New Framework** - *Sveobuhvatan pregled metoda za analizu teksta u dru코tvenim znanostima. Autori su Grimmer, Roberts i Stewart.* [Link](https://textasdata.com/)

**Statistika i razumijevanje podataka:**

*   **How to Lie with Statistics** - *Klasi캜na i zabavna knjiga Darrella Huffa o tome kako prepoznati manipulaciju statistikom.* [Link](https://archive.org/details/how-to-lie-with-statistics-darrell-huff/page/n5/mode/2up)
*   **The Art of Statistics: Learning from Data** - *David Spiegelhalter na pristupa캜an na캜in obja코njava kako statisti캜ari razmi코ljaju i kako u캜iti iz podataka.* [Link](https://www.bookdepository.com/Art-Statistics-David-Spiegelhalter/9780241258767)

---

#### 游깴 Podaci i resursi za tematska istra쬴vanja

Linkovi na relevantne izvore podataka, 캜asopise i organizacije koje se bave sli캜nim temama.

*   **Pew Research Center: Religion & Public Life** - *Jedan od najva쬹ijih izvora podataka i analiza o ulozi religije u dru코tvu.* [Link](https://www.pewresearch.org/religion/)
*   **Journal of Media and Religion** - *Vode캖i znanstveni 캜asopis koji objavljuje istra쬴vanja na sjeci코tu medija i religije.* [Link](https://www.tandfonline.com/journals/hmre20)
*   **Alliance of Digital Humanities Organizations (ADHO)** - *Globalna organizacija koja promi캜e primjenu digitalnih tehnologija u humanisti캜kim znanostima.* [Link](https://adho.org/)

---

#### 游깷 Blogovi, zajednice i platforme

Mjesta za u캜enje, postavljanje pitanja i pra캖enje najnovijih trendova.

*   **Towards Data Science** - *Jedna od najve캖ih online publikacija o podatkovnoj znanosti, s tisu캖ama korisnih 캜lanaka i tutorijala.* [Link](https://towardsdatascience.com/)
*   **Stack Overflow** - *Najva쬹ija zajednica za programere. Ako imate tehni캜ki problem, ovdje 캖ete najvjerojatnije prona캖i odgovor.* [Link](https://stackoverflow.com/)
*   **GitHub** - *Platforma na kojoj se nalazi ovaj projekt. Klju캜an alat za otvorenu znanost, suradnju i dijeljenje koda.* [Link](https://github.com/)
*   **Zenodo** - *Otvoreni repozitorij za pohranu znanstvenih podataka, softvera i publikacija, u skladu s FAIR principima.* [Link](https://zenodo.org/)

    
<br>
<br>
<br>

