---
title: "Katalog izvora"
subtitle: "Profili pojedinačnih medijskih aktera"
date: last-modified
categories: ["Katalog izvora", "Baza podataka"]
---

**Katalog izvora** pregled je pojedinačnih medijskih aktera zastupljenih u korpusu. Dio je opisa [Baze podataka](../baza.html), a tipologiju izvora dijeli s [Mapom ekosustava](../mapa/mapa.html). Za svaki izvor donosi volumen, angažman i doseg te pripadnost tipologiji (Divovi, Graditelji zajednica, Megafoni, Specijalizirani akteri), izračunatoj jednako kao u Mapi.

Cijeli se katalog može vidjeti i kao [mreža izvora](mreza.html) — čvorovi su izvori, a poveznice pripadnost platformi i zajednički brend.

::: {.callout-note}
Podaci dolaze iz agregata `data/processed/*_actors.rds` (bez osobnih podataka). Katalog je **radna verzija**: uređivačke oznake (konfesionalni/sekularni izvor) prijedlozi su koje potvrđuje voditelj projekta, a brojke su indikativne (statični agregati; mnogi akteri na novim platformama imaju tek nekoliko objava). Trenutno je objavljeno **103** izvora; **11** aktera zadržano je za uredničku provjeru.
:::

## Web

Praćeni izvori na platformi Web (poredano po volumenu). Cjeloviti pregled: [Web](platforma-web.html).

| Izvor | Tipologija | Objava | Interakcija |
|---|---|---:|---:|
| [hkm.hr](web-hkm-hr.html) | Divovi | 56.500 | 3.090.701 |
| [slobodnadalmacija.hr](web-slobodnadalmacija-hr.html) | Divovi | 12.662 | 1.494.818 |
| [laudato.hr](web-laudato-hr.html) | Specijalizirani akteri | 11.979 | 713.352 |
| [vecernji.hr](web-vecernji-hr.html) | Divovi | 10.309 | 1.630.331 |
| [index.hr](web-index-hr.html) | Divovi | 9.698 | 3.389.428 |
| [net.hr](web-net-hr.html) | Megafoni | 9.167 | 793.686 |
| [jutarnji.hr](web-jutarnji-hr.html) | Divovi | 8.977 | 1.638.768 |
| [24sata.hr](web-24sata-hr.html) | Divovi | 7.992 | 1.745.424 |
| [novizivot.net](web-novizivot-net.html) | Divovi | 7.496 | 3.796.197 |
| [tportal.hr](web-tportal-hr.html) | Specijalizirani akteri | 6.340 | 187.988 |
| [narod.hr](web-narod-hr.html) | Specijalizirani akteri | 6.205 | 620.369 |
| [dnevno.hr](web-dnevno-hr.html) | Divovi | 5.752 | 3.289.102 |
| [dnevnik.hr](web-dnevnik-hr.html) | Divovi | 5.551 | 959.448 |
| [bitno.net](web-bitno-net.html) | Specijalizirani akteri | 4.485 | 820.025 |
| [dalmatinskiportal.hr](web-dalmatinskiportal-hr.html) | Specijalizirani akteri | 4.096 | 507.926 |
| [telegram.hr](web-telegram-hr.html) | Graditelji zajednica | 3.535 | 1.204.056 |
| [mnovine.hr](web-mnovine-hr.html) | Specijalizirani akteri | 1.996 | 343.170 |
| [caritas.hr](web-caritas-hr.html) | Specijalizirani akteri | 225 | 580.472 |

## YouTube

Praćeni izvori na platformi YouTube (poredano po volumenu). Cjeloviti pregled: [YouTube](platforma-youtube.html).

| Izvor | Tipologija | Objava | Interakcija |
|---|---|---:|---:|
| [pulherissimus](youtube-pulherissimus.html) | Divovi | 6.042 | 1.621.368 |
| [LaudatoTV](youtube-laudatotv.html) | Divovi | 4.064 | 170.409 |
| [Hrana za dušu](youtube-hrana-za-dusu.html) | Divovi | 3.457 | 462.317 |
| [Dijete Vjere](youtube-dijete-vjere.html) | Graditelji zajednica | 1.934 | 444.695 |
| [Pod Smokvom](youtube-pod-smokvom.html) | Graditelji zajednica | 1.522 | 589.626 |
| [Nova Eva](youtube-nova-eva.html) | Megafoni | 667 | 94.921 |
| [Stopama Padre Pija](youtube-stopama-padre-pija.html) | Specijalizirani akteri | 407 | 104.504 |
| [RTL](youtube-rtl.html) | Specijalizirani akteri | 373 | 47.613 |
| [Majko Marijo](youtube-majko-marijo.html) | Divovi | 333 | 266.210 |
| [BOŽANSKA LJUBAV](youtube-bozanska-ljubav.html) | Graditelji zajednica | 152 | 144.742 |
| [budiFRAjer](youtube-budifrajer.html) | Specijalizirani akteri | 152 | 118.891 |
| [Bog Je Tu](youtube-bog-je-tu.html) | Specijalizirani akteri | 93 | 93.696 |

## Facebook

Praćeni izvori na platformi Facebook (poredano po volumenu). Cjeloviti pregled: [Facebook](platforma-facebook.html).

| Izvor | Tipologija | Objava | Interakcija |
|---|---|---:|---:|
| [VJERA U NAMA †](facebook-vjera-u-nama.html) | Graditelji zajednica | 5.326 | 255.466 |
| [Bitno.net](facebook-bitno-net.html) | Divovi | 4.132 | 698.950 |
| [Radio Marija Hrvatska](facebook-radio-marija-hrvatska.html) | Specijalizirani akteri | 3.481 | 191.275 |
| [Laudato](facebook-laudato.html) | Divovi | 2.512 | 1.081.728 |
| [Zagrebačka nadbiskupija](facebook-zagrebacka-nadbiskupija.html) | Graditelji zajednica | 2.251 | 285.393 |
| [Kapljice ljubavi Božje](facebook-kapljice-ljubavi-bozje.html) | Graditelji zajednica | 1.894 | 399.514 |
| [Kraljica Mira](facebook-kraljica-mira.html) | Specijalizirani akteri | 1.456 | 167.054 |
| [VJERA](facebook-vjera.html) | Graditelji zajednica | 1.298 | 405.078 |
| [Slobodna Dalmacija](facebook-slobodna-dalmacija.html) | Megafoni | 992 | 142.757 |
| [Gospa](facebook-gospa.html) | Graditelji zajednica | 873 | 214.302 |
| [RTL Danas](facebook-rtl-danas.html) | Megafoni | 798 | 196.740 |
| [Net.hr](facebook-net-hr.html) | Megafoni | 764 | 145.782 |
| [DNEVNIK.hr](facebook-dnevnik-hr.html) | Megafoni | 730 | 180.136 |
| [Večernji list](facebook-vecernji-list.html) | Megafoni | 692 | 126.214 |
| [24sata](facebook-24sata.html) | Divovi | 630 | 207.441 |
| [Index.hr](facebook-index-hr.html) | Divovi | 365 | 227.035 |
| [Jutarnji](facebook-jutarnji.html) | Specijalizirani akteri | 326 | 89.926 |

## Instagram

Praćeni izvori na platformi Instagram (poredano po volumenu). Cjeloviti pregled: [Instagram](platforma-instagram.html).

| Izvor | Tipologija | Objava | Interakcija |
|---|---|---:|---:|
| [dnevniavaz](instagram-dnevniavaz.html) | Divovi | 51 | 24.181 |
| [laudatotv](instagram-laudatotv.html) | Divovi | 42 | 50.276 |
| [ivan.anusic.hr](instagram-ivan-anusic-hr.html) | Specijalizirani akteri | 13 | 8.822 |
| [_rina.rs](instagram-rina-rs.html) | Divovi | 6 | 10.773 |
| [hrvatskivojnik_magazin](instagram-hrvatskivojnik-magazin.html) | Specijalizirani akteri | 6 | 6.246 |
| [oslobodjenje.ba](instagram-oslobodjenje-ba.html) | Specijalizirani akteri | 4 | 6.268 |
| [24sata.hr](instagram-24sata-hr.html) | Megafoni | 4 | 6.157 |
| [insidebosnia](instagram-insidebosnia.html) | Graditelji zajednica | 3 | 9.715 |
| [buducnostsrbijeav](instagram-buducnostsrbijeav.html) | Megafoni | 3 | 9.341 |
| [kristijanilicic](instagram-kristijanilicic.html) | Divovi | 2 | 22.590 |
| [sport.klub](instagram-sport-klub.html) | Megafoni | 2 | 6.624 |
| [hns_cff](instagram-hns-cff.html) | Divovi | 1 | 52.022 |
| [martinafilic](instagram-martinafilic.html) | Graditelji zajednica | 1 | 13.655 |
| [ekostraza](instagram-ekostraza.html) | Graditelji zajednica | 1 | 12.286 |
| [klaskalica](instagram-klaskalica.html) | Graditelji zajednica | 1 | 10.238 |
| [elladvornik](instagram-elladvornik.html) | Megafoni | 1 | 7.510 |
| [zenskisvijet](instagram-zenskisvijet.html) | Specijalizirani akteri | 1 | 6.928 |
| [vannabojovic](instagram-vannabojovic.html) | Specijalizirani akteri | 1 | 6.847 |

## TikTok

Praćeni izvori na platformi TikTok (poredano po volumenu). Cjeloviti pregled: [TikTok](platforma-tiktok.html).

| Izvor | Tipologija | Objava | Interakcija |
|---|---|---:|---:|
| [dnevnikhr](tiktok-dnevnikhr.html) | Divovi | 28 | 20.673 |
| [24sata](tiktok-24sata.html) | Divovi | 27 | 28.162 |
| [vecernjilist](tiktok-vecernjilist.html) | Divovi | 27 | 19.725 |
| [hrvatska_radiotelevizija](tiktok-hrvatska-radiotelevizija.html) | Divovi | 26 | 50.002 |
| [trtbalkanbhsc](tiktok-trtbalkanbhsc.html) | Divovi | 22 | 18.082 |
| [slobodna.dalmacija](tiktok-slobodna-dalmacija.html) | Divovi | 14 | 45.133 |
| [kristijanilicic](tiktok-kristijanilicic.html) | Divovi | 8 | 63.266 |
| [index.hr](tiktok-index-hr.html) | Divovi | 6 | 33.151 |
| [shkm2026](tiktok-shkm2026.html) | Specijalizirani akteri | 5 | 7.374 |
| [mladifesthrvatska](tiktok-mladifesthrvatska.html) | Specijalizirani akteri | 4 | 10.870 |
| [rtldirekt](tiktok-rtldirekt.html) | Divovi | 3 | 29.504 |
| [poslanik.gospodina](tiktok-poslanik-gospodina.html) | Megafoni | 3 | 15.639 |
| [crovibes](tiktok-crovibes.html) | Specijalizirani akteri | 3 | 5.728 |
| [plenkovic_andrej](tiktok-plenkovic-andrej.html) | Specijalizirani akteri | 2 | 5.790 |
| [dontomolukac](tiktok-dontomolukac.html) | Graditelji zajednica | 1 | 40.752 |
| [kamenkrsislanina](tiktok-kamenkrsislanina.html) | Specijalizirani akteri | 1 | 13.400 |
| [hypetelevizija.hr](tiktok-hypetelevizija-hr.html) | Specijalizirani akteri | 1 | 10.991 |
| [mondo.zabava](tiktok-mondo-zabava.html) | Specijalizirani akteri | 1 | 6.268 |
| [euforija.online](tiktok-euforija-online.html) | Specijalizirani akteri | 1 | 5.646 |

## Twitter

Praćeni izvori na platformi Twitter (poredano po volumenu). Cjeloviti pregled: [Twitter](platforma-twitter.html).

| Izvor | Tipologija | Objava | Interakcija |
|---|---|---:|---:|
| [Zagrebačka nadbiskupija](twitter-zagrebacka-nadbiskupija.html) | Megafoni | 75 | 984 |
| [Petar](twitter-petar.html) | Divovi | 73 | 2.247 |
| [Vlada Republike Hrvatske](twitter-vlada-republike-hrvatske.html) | Divovi | 65 | 2.599 |
| [Andrej Plenković](twitter-andrej-plenkovic.html) | Divovi | 35 | 3.928 |
| [Darko Lesinger](twitter-darko-lesinger.html) | Megafoni | 15 | 991 |
| [Hrvatski Kanal](twitter-hrvatski-kanal.html) | Specijalizirani akteri | 15 | 822 |
| [Stephen Nikola Bartulica](twitter-stephen-nikola-bartulica.html) | Divovi | 14 | 1.802 |
| [Pavel Gregoric](twitter-pavel-gregoric.html) | Divovi | 12 | 1.314 |
| [Mate Mijić 🇭🇷](twitter-mate-mijic.html) | Specijalizirani akteri | 9 | 783 |
| [Ivan Anušić](twitter-ivan-anusic.html) | Divovi | 8 | 1.249 |
| [Dominik Alpeza](twitter-dominik-alpeza.html) | Specijalizirani akteri | 6 | 965 |
| [Dalija Orešković](twitter-dalija-oreskovic.html) | Specijalizirani akteri | 6 | 834 |
| [Vesna Rajnović 🌿](twitter-vesna-rajnovic.html) | Specijalizirani akteri | 6 | 767 |
| [Marin Miletić](twitter-marin-miletic.html) | Specijalizirani akteri | 4 | 850 |
| [Željka Markić](twitter-zeljka-markic.html) | Graditelji zajednica | 3 | 1.028 |
| [NORWEGIAN MAN](twitter-norwegian-man.html) | Divovi | 2 | 1.509 |
| [Neven Barkovic](twitter-neven-barkovic.html) | Graditelji zajednica | 2 | 1.110 |
| [Mk.gee 🇪🇺](twitter-mk-gee.html) | Specijalizirani akteri | 2 | 905 |
| [Laganica](twitter-laganica.html) | Divovi | 1 | 3.385 |

