<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-01-20">

<title>general_catholic_media – DigiKat</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-82c9f8657cf8f03ee2a5875e7c1d7df8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../assets/css/style.css">
<link rel="stylesheet" href="../assets/css/custom.scss">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">DigiKat</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../pages/index.html"> 
<span class="menu-text">Osnovne informacije</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/about.html"> 
<span class="menu-text">O projektu</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/schedule.html"> 
<span class="menu-text">Projektni raspored</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/baza.html"> 
<span class="menu-text">Baza podataka</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-mapa-medijskog-prostora" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Mapa medijskog prostora</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-mapa-medijskog-prostora">    
        <li>
    <a class="dropdown-item" href="../pages/mapa/mapa.html">
 <span class="dropdown-text">Mapa ekosustava</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../pages/mapa/mapa_stats.html">
 <span class="dropdown-text">Tematske struje</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../pages/mapa/diskurs.html">
 <span class="dropdown-text">Atmosfera diskursa</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../pages/mapa/događaji.html">
 <span class="dropdown-text">Fokus na događaje i kampanje</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tematska-istraživanja" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tematska istraživanja</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tematska-istraživanja">    
        <li class="dropdown-header">Analiza self-help sadržaja na YouTube-u</li>
        <li class="dropdown-header">Hodočasnički turizam</li>
        <li class="dropdown-header">Demokršćanstvo</li>
        <li class="dropdown-header">Katoličko obrazovanje</li>
        <li class="dropdown-header">Prikazivanje katoličkih svetaca i svetica</li>
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../pages/news.html"> 
<span class="menu-text">Obavijesti</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pages/resources.html"> 
<span class="menu-text">Resursi</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../pages/site-info.html"> 
<span class="menu-text">O stranici</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/lusiki/DigiKat"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#i.-dio-povijesni-i-institucionalni-okvir" id="toc-i.-dio-povijesni-i-institucionalni-okvir" class="nav-link active" data-scroll-target="#i.-dio-povijesni-i-institucionalni-okvir">I. DIO: POVIJESNI I INSTITUCIONALNI OKVIR</a>
  <ul class="collapse">
  <li><a href="#uvod" id="toc-uvod" class="nav-link" data-scroll-target="#uvod">Uvod</a>
  <ul class="collapse">
  <li><a href="#opseg-analize" id="toc-opseg-analize" class="nav-link" data-scroll-target="#opseg-analize">Opseg analize</a></li>
  </ul></li>
  <li><a href="#povijesni-temelji" id="toc-povijesni-temelji" class="nav-link" data-scroll-target="#povijesni-temelji">Povijesni temelji</a>
  <ul class="collapse">
  <li><a href="#od-prvih-izdanja-do-komunističke-represije-1849.1945." id="toc-od-prvih-izdanja-do-komunističke-represije-1849.1945." class="nav-link" data-scroll-target="#od-prvih-izdanja-do-komunističke-represije-1849.1945.">Od prvih izdanja do komunističke represije (1849.–1945.)</a></li>
  <li><a href="#otpor-i-opstanak-u-jugoslavenskom-razdoblju-1945.1991." id="toc-otpor-i-opstanak-u-jugoslavenskom-razdoblju-1945.1991." class="nav-link" data-scroll-target="#otpor-i-opstanak-u-jugoslavenskom-razdoblju-1945.1991.">Otpor i opstanak u jugoslavenskom razdoblju (1945.–1991.)</a></li>
  <li><a href="#ekspanzija-nakon-neovisnosti-1991.2018." id="toc-ekspanzija-nakon-neovisnosti-1991.2018." class="nav-link" data-scroll-target="#ekspanzija-nakon-neovisnosti-1991.2018.">Ekspanzija nakon neovisnosti (1991.–2018.)</a></li>
  </ul></li>
  <li><a href="#suvremena-medijska-infrastruktura" id="toc-suvremena-medijska-infrastruktura" class="nav-link" data-scroll-target="#suvremena-medijska-infrastruktura">Suvremena medijska infrastruktura</a>
  <ul class="collapse">
  <li><a href="#hrvatska-katolička-mreža-kao-integracijska-platforma" id="toc-hrvatska-katolička-mreža-kao-integracijska-platforma" class="nav-link" data-scroll-target="#hrvatska-katolička-mreža-kao-integracijska-platforma">Hrvatska katolička mreža kao integracijska platforma</a></li>
  <li><a href="#emitiranje-kao-okosnica-komunikacije" id="toc-emitiranje-kao-okosnica-komunikacije" class="nav-link" data-scroll-target="#emitiranje-kao-okosnica-komunikacije">Emitiranje kao okosnica komunikacije</a></li>
  <li><a href="#izdavačka-infrastruktura" id="toc-izdavačka-infrastruktura" class="nav-link" data-scroll-target="#izdavačka-infrastruktura">Izdavačka infrastruktura</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#ii.-dio-biskupijska-struktura" id="toc-ii.-dio-biskupijska-struktura" class="nav-link" data-scroll-target="#ii.-dio-biskupijska-struktura">II. DIO: BISKUPIJSKA STRUKTURA</a>
  <ul class="collapse">
  <li><a href="#metropolitanske-nadbiskupije" id="toc-metropolitanske-nadbiskupije" class="nav-link" data-scroll-target="#metropolitanske-nadbiskupije">Metropolitanske nadbiskupije</a>
  <ul class="collapse">
  <li><a href="#zagrebačka-nadbiskupija" id="toc-zagrebačka-nadbiskupija" class="nav-link" data-scroll-target="#zagrebačka-nadbiskupija">Zagrebačka nadbiskupija</a></li>
  <li><a href="#splitsko-makarska-nadbiskupija" id="toc-splitsko-makarska-nadbiskupija" class="nav-link" data-scroll-target="#splitsko-makarska-nadbiskupija">Splitsko-makarska nadbiskupija</a></li>
  <li><a href="#đakovačko-osječka-nadbiskupija" id="toc-đakovačko-osječka-nadbiskupija" class="nav-link" data-scroll-target="#đakovačko-osječka-nadbiskupija">Đakovačko-osječka nadbiskupija</a></li>
  <li><a href="#riječka-nadbiskupija" id="toc-riječka-nadbiskupija" class="nav-link" data-scroll-target="#riječka-nadbiskupija">Riječka nadbiskupija</a></li>
  </ul></li>
  <li><a href="#sufraganske-biskupije" id="toc-sufraganske-biskupije" class="nav-link" data-scroll-target="#sufraganske-biskupije">Sufraganske biskupije</a>
  <ul class="collapse">
  <li><a href="#biskupije-s-najsnažnijom-digitalnom-prisutnošću" id="toc-biskupije-s-najsnažnijom-digitalnom-prisutnošću" class="nav-link" data-scroll-target="#biskupije-s-najsnažnijom-digitalnom-prisutnošću">Biskupije s najsnažnijom digitalnom prisutnošću</a></li>
  <li><a href="#kompletni-pregled-digitalnih-kapaciteta-svih-biskupija" id="toc-kompletni-pregled-digitalnih-kapaciteta-svih-biskupija" class="nav-link" data-scroll-target="#kompletni-pregled-digitalnih-kapaciteta-svih-biskupija">Kompletni pregled digitalnih kapaciteta svih biskupija</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#iii.-dio-redovničke-zajednice" id="toc-iii.-dio-redovničke-zajednice" class="nav-link" data-scroll-target="#iii.-dio-redovničke-zajednice">III. DIO: REDOVNIČKE ZAJEDNICE</a>
  <ul class="collapse">
  <li><a href="#franjevačke-zajednice" id="toc-franjevačke-zajednice" class="nav-link" data-scroll-target="#franjevačke-zajednice">Franjevačke zajednice</a>
  <ul class="collapse">
  <li><a href="#provincija-presvetog-otkupitelja-ofm-split" id="toc-provincija-presvetog-otkupitelja-ofm-split" class="nav-link" data-scroll-target="#provincija-presvetog-otkupitelja-ofm-split">Provincija Presvetog Otkupitelja (OFM, Split)</a></li>
  <li><a href="#franjevci-konventualci-ofmconv" id="toc-franjevci-konventualci-ofmconv" class="nav-link" data-scroll-target="#franjevci-konventualci-ofmconv">Franjevci konventualci (OFMConv)</a></li>
  <li><a href="#kapucini-ofmcap" id="toc-kapucini-ofmcap" class="nav-link" data-scroll-target="#kapucini-ofmcap">Kapucini (OFMCap)</a></li>
  </ul></li>
  <li><a href="#isusovci-družba-isusova" id="toc-isusovci-družba-isusova" class="nav-link" data-scroll-target="#isusovci-družba-isusova">Isusovci (Družba Isusova)</a></li>
  <li><a href="#dominikanci" id="toc-dominikanci" class="nav-link" data-scroll-target="#dominikanci">Dominikanci</a></li>
  <li><a href="#salezijanci" id="toc-salezijanci" class="nav-link" data-scroll-target="#salezijanci">Salezijanci</a></li>
  <li><a href="#benediktinci-i-trapisti" id="toc-benediktinci-i-trapisti" class="nav-link" data-scroll-target="#benediktinci-i-trapisti">Benediktinci i trapisti</a></li>
  </ul></li>
  <li><a href="#iv.-dio-akademski-katolički-mediji" id="toc-iv.-dio-akademski-katolički-mediji" class="nav-link" data-scroll-target="#iv.-dio-akademski-katolički-mediji">IV. DIO: AKADEMSKI KATOLIČKI MEDIJI</a>
  <ul class="collapse">
  <li><a href="#časopisi-s-međunarodnom-indeksacijom" id="toc-časopisi-s-međunarodnom-indeksacijom" class="nav-link" data-scroll-target="#časopisi-s-međunarodnom-indeksacijom">Časopisi s međunarodnom indeksacijom</a>
  <ul class="collapse">
  <li><a href="#bogoslovska-smotra" id="toc-bogoslovska-smotra" class="nav-link" data-scroll-target="#bogoslovska-smotra">Bogoslovska smotra</a></li>
  <li><a href="#obnovljeni-život" id="toc-obnovljeni-život" class="nav-link" data-scroll-target="#obnovljeni-život">Obnovljeni život</a></li>
  <li><a href="#crkva-u-svijetu" id="toc-crkva-u-svijetu" class="nav-link" data-scroll-target="#crkva-u-svijetu">Crkva u svijetu</a></li>
  <li><a href="#diacovensia" id="toc-diacovensia" class="nav-link" data-scroll-target="#diacovensia">Diacovensia</a></li>
  <li><a href="#pregled-svih-akademskih-časopisa" id="toc-pregled-svih-akademskih-časopisa" class="nav-link" data-scroll-target="#pregled-svih-akademskih-časopisa">Pregled svih akademskih časopisa</a></li>
  </ul></li>
  <li><a href="#hrvatsko-katoličko-sveučilište" id="toc-hrvatsko-katoličko-sveučilište" class="nav-link" data-scroll-target="#hrvatsko-katoličko-sveučilište">Hrvatsko katoličko sveučilište</a></li>
  <li><a href="#katolički-bogoslovni-fakultet-zagreb" id="toc-katolički-bogoslovni-fakultet-zagreb" class="nav-link" data-scroll-target="#katolički-bogoslovni-fakultet-zagreb">Katolički bogoslovni fakultet Zagreb</a></li>
  </ul></li>
  <li><a href="#v.-dio-pastoral-mladih" id="toc-v.-dio-pastoral-mladih" class="nav-link" data-scroll-target="#v.-dio-pastoral-mladih">V. DIO: PASTORAL MLADIH</a>
  <ul class="collapse">
  <li><a href="#susret-hrvatske-katoličke-mladeži-shkm" id="toc-susret-hrvatske-katoličke-mladeži-shkm" class="nav-link" data-scroll-target="#susret-hrvatske-katoličke-mladeži-shkm">Susret hrvatske katoličke mladeži (SHKM)</a>
  <ul class="collapse">
  <li><a href="#shkm-2026-digitalna-infrastruktura" id="toc-shkm-2026-digitalna-infrastruktura" class="nav-link" data-scroll-target="#shkm-2026-digitalna-infrastruktura">SHKM 2026 digitalna infrastruktura</a></li>
  </ul></li>
  <li><a href="#frama-franjevačka-mladež" id="toc-frama-franjevačka-mladež" class="nav-link" data-scroll-target="#frama-franjevačka-mladež">FRAMA (Franjevačka mladež)</a></li>
  <li><a href="#katolički-skauti-hrvatske" id="toc-katolički-skauti-hrvatske" class="nav-link" data-scroll-target="#katolički-skauti-hrvatske">Katolički skauti Hrvatske</a></li>
  <li><a href="#taizé-zajednica" id="toc-taizé-zajednica" class="nav-link" data-scroll-target="#taizé-zajednica">Taizé zajednica</a></li>
  <li><a href="#medijski-programi-za-mlade" id="toc-medijski-programi-za-mlade" class="nav-link" data-scroll-target="#medijski-programi-za-mlade">Medijski programi za mlade</a>
  <ul class="collapse">
  <li><a href="#laudato-tv-generacija" id="toc-laudato-tv-generacija" class="nav-link" data-scroll-target="#laudato-tv-generacija">Laudato TV — Generacija+</a></li>
  <li><a href="#hrvatski-katolički-radio" id="toc-hrvatski-katolički-radio" class="nav-link" data-scroll-target="#hrvatski-katolički-radio">Hrvatski katolički radio</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#vi.-dio-hrvatska-katolička-dijaspora" id="toc-vi.-dio-hrvatska-katolička-dijaspora" class="nav-link" data-scroll-target="#vi.-dio-hrvatska-katolička-dijaspora">VI. DIO: HRVATSKA KATOLIČKA DIJASPORA</a>
  <ul class="collapse">
  <li><a href="#globalna-struktura" id="toc-globalna-struktura" class="nav-link" data-scroll-target="#globalna-struktura">Globalna struktura</a>
  <ul class="collapse">
  <li><a href="#pastoralno-osoblje" id="toc-pastoralno-osoblje" class="nav-link" data-scroll-target="#pastoralno-osoblje">Pastoralno osoblje</a></li>
  </ul></li>
  <li><a href="#digitalna-prisutnost-dijaspore" id="toc-digitalna-prisutnost-dijaspore" class="nav-link" data-scroll-target="#digitalna-prisutnost-dijaspore">Digitalna prisutnost dijaspore</a>
  <ul class="collapse">
  <li><a href="#njemačka" id="toc-njemačka" class="nav-link" data-scroll-target="#njemačka">Njemačka</a></li>
  <li><a href="#švicarska" id="toc-švicarska" class="nav-link" data-scroll-target="#švicarska">Švicarska</a></li>
  <li><a href="#austrija" id="toc-austrija" class="nav-link" data-scroll-target="#austrija">Austrija</a></li>
  <li><a href="#australija" id="toc-australija" class="nav-link" data-scroll-target="#australija">Australija</a></li>
  <li><a href="#sad" id="toc-sad" class="nav-link" data-scroll-target="#sad">SAD</a></li>
  <li><a href="#koordinacija" id="toc-koordinacija" class="nav-link" data-scroll-target="#koordinacija">Koordinacija</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#vii.-dio-digitalna-prisutnost" id="toc-vii.-dio-digitalna-prisutnost" class="nav-link" data-scroll-target="#vii.-dio-digitalna-prisutnost">VII. DIO: DIGITALNA PRISUTNOST</a>
  <ul class="collapse">
  <li><a href="#web-portali" id="toc-web-portali" class="nav-link" data-scroll-target="#web-portali">Web portali</a>
  <ul class="collapse">
  <li><a href="#hijerarhija-digitalnih-platformi" id="toc-hijerarhija-digitalnih-platformi" class="nav-link" data-scroll-target="#hijerarhija-digitalnih-platformi">Hijerarhija digitalnih platformi</a></li>
  </ul></li>
  <li><a href="#društvene-mreže" id="toc-društvene-mreže" class="nav-link" data-scroll-target="#društvene-mreže">Društvene mreže</a>
  <ul class="collapse">
  <li><a href="#prisutnost-na-instagramu-verificirani-podaci" id="toc-prisutnost-na-instagramu-verificirani-podaci" class="nav-link" data-scroll-target="#prisutnost-na-instagramu-verificirani-podaci">Prisutnost na Instagramu (verificirani podaci)</a></li>
  </ul></li>
  <li><a href="#youtube-i-video-sadržaj" id="toc-youtube-i-video-sadržaj" class="nav-link" data-scroll-target="#youtube-i-video-sadržaj">YouTube i video sadržaj</a></li>
  <li><a href="#tiktok-kao-nova-granica" id="toc-tiktok-kao-nova-granica" class="nav-link" data-scroll-target="#tiktok-kao-nova-granica">TikTok kao nova granica</a></li>
  <li><a href="#podcasti" id="toc-podcasti" class="nav-link" data-scroll-target="#podcasti">Podcasti</a></li>
  <li><a href="#mobilne-aplikacije" id="toc-mobilne-aplikacije" class="nav-link" data-scroll-target="#mobilne-aplikacije">Mobilne aplikacije</a>
  <ul class="collapse">
  <li><a href="#službene-institucionalne-aplikacije" id="toc-službene-institucionalne-aplikacije" class="nav-link" data-scroll-target="#službene-institucionalne-aplikacije">Službene institucionalne aplikacije</a></li>
  <li><a href="#biblijske-aplikacije" id="toc-biblijske-aplikacije" class="nav-link" data-scroll-target="#biblijske-aplikacije">Biblijske aplikacije</a></li>
  <li><a href="#molitvene-i-duhovne-aplikacije" id="toc-molitvene-i-duhovne-aplikacije" class="nav-link" data-scroll-target="#molitvene-i-duhovne-aplikacije">Molitvene i duhovne aplikacije</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#viii.-dio-utjecaj-digitalne-transformacije" id="toc-viii.-dio-utjecaj-digitalne-transformacije" class="nav-link" data-scroll-target="#viii.-dio-utjecaj-digitalne-transformacije">VIII. DIO: UTJECAJ DIGITALNE TRANSFORMACIJE</a>
  <ul class="collapse">
  <li><a href="#covid-19-kao-katalizator" id="toc-covid-19-kao-katalizator" class="nav-link" data-scroll-target="#covid-19-kao-katalizator">COVID-19 kao katalizator</a>
  <ul class="collapse">
  <li><a href="#online-prijenosi-misa" id="toc-online-prijenosi-misa" class="nav-link" data-scroll-target="#online-prijenosi-misa">Online prijenosi misa</a></li>
  </ul></li>
  <li><a href="#transformacija-tiskanih-medija" id="toc-transformacija-tiskanih-medija" class="nav-link" data-scroll-target="#transformacija-tiskanih-medija">Transformacija tiskanih medija</a>
  <ul class="collapse">
  <li><a href="#glas-koncila" id="toc-glas-koncila" class="nav-link" data-scroll-target="#glas-koncila">Glas Koncila</a></li>
  </ul></li>
  <li><a href="#digitalne-platforme-za-župno-poslovanje" id="toc-digitalne-platforme-za-župno-poslovanje" class="nav-link" data-scroll-target="#digitalne-platforme-za-župno-poslovanje">Digitalne platforme za župno poslovanje</a>
  <ul class="collapse">
  <li><a href="#e-župe-sustav" id="toc-e-župe-sustav" class="nav-link" data-scroll-target="#e-župe-sustav">E-župe sustav</a></li>
  <li><a href="#virtualna-hodočašća" id="toc-virtualna-hodočašća" class="nav-link" data-scroll-target="#virtualna-hodočašća">Virtualna hodočašća</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#ix.-dio-ključni-akteri" id="toc-ix.-dio-ključni-akteri" class="nav-link" data-scroll-target="#ix.-dio-ključni-akteri">IX. DIO: KLJUČNI AKTERI</a>
  <ul class="collapse">
  <li><a href="#institucionalni-akteri" id="toc-institucionalni-akteri" class="nav-link" data-scroll-target="#institucionalni-akteri">Institucionalni akteri</a></li>
  <li><a href="#individualni-akteri-svećenici-na-društvenim-mrežama" id="toc-individualni-akteri-svećenici-na-društvenim-mrežama" class="nav-link" data-scroll-target="#individualni-akteri-svećenici-na-društvenim-mrežama">Individualni akteri — svećenici na društvenim mrežama</a></li>
  <li><a href="#laički-influenceri" id="toc-laički-influenceri" class="nav-link" data-scroll-target="#laički-influenceri">Laički influenceri</a></li>
  <li><a href="#laičke-zajednice-i-pokreti" id="toc-laičke-zajednice-i-pokreti" class="nav-link" data-scroll-target="#laičke-zajednice-i-pokreti">Laičke zajednice i pokreti</a></li>
  <li><a href="#katolička-glazbena-scena" id="toc-katolička-glazbena-scena" class="nav-link" data-scroll-target="#katolička-glazbena-scena">Katolička glazbena scena</a></li>
  </ul></li>
  <li><a href="#x.-dio-financiranje-i-održivost" id="toc-x.-dio-financiranje-i-održivost" class="nav-link" data-scroll-target="#x.-dio-financiranje-i-održivost">X. DIO: FINANCIRANJE I ODRŽIVOST</a>
  <ul class="collapse">
  <li><a href="#strukturni-izazovi" id="toc-strukturni-izazovi" class="nav-link" data-scroll-target="#strukturni-izazovi">Strukturni izazovi</a></li>
  <li><a href="#prednost-povjerenja" id="toc-prednost-povjerenja" class="nav-link" data-scroll-target="#prednost-povjerenja">Prednost povjerenja</a></li>
  <li><a href="#zaključak" id="toc-zaključak" class="nav-link" data-scroll-target="#zaključak">Zaključak</a>
  <ul class="collapse">
  <li><a href="#ključni-nalazi" id="toc-ključni-nalazi" class="nav-link" data-scroll-target="#ključni-nalazi">Ključni nalazi</a></li>
  <li><a href="#strateški-nedostaci" id="toc-strateški-nedostaci" class="nav-link" data-scroll-target="#strateški-nedostaci">Strateški nedostaci</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">general_catholic_media</h1>
<p class="subtitle lead">Sveobuhvatna strukturalna analiza</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div style="text-align: center; margin-bottom: 30px;">
<p><img src="https://img.shields.io/badge/status-aktivan-green.png" class="img-fluid" alt="Status"> <img src="https://img.shields.io/badge/tip-strukturalna_analiza-blue.png" class="img-fluid" alt="Tip"> <img src="https://img.shields.io/badge/verzija-3.0-lightgrey" class="img-fluid" alt="Verzija"></p>
</div>
<blockquote class="blockquote">
<p><strong>Sažetak:</strong> Ovaj dokument pruža sveobuhvatnu strukturalnu analizu hrvatskog katoličkog medijskog ekosustava sa posebnim naglaskom na njgov digitalni segment. Sintezom 173 godine izdavačke tradicije, analizom svih 17 biskupija, redovničkih zajednica, akademskih časopisa, pastorala mladih, 189 misija u dijaspori te utjecaja digitalne transformacije, dokument mapira ekosustav koji seže od župnih biltena do nacionalno licencirane televizije. Služi kao kontekstualni okvir za razumijevanje kvantitativnih nalaza iz četiri analitičke mape projekta DigiKat.</p>
</blockquote>
<hr>
<section id="i.-dio-povijesni-i-institucionalni-okvir" class="level1">
<h1>I. DIO: POVIJESNI I INSTITUCIONALNI OKVIR</h1>
<section id="uvod" class="level2">
<h2 class="anchored" data-anchor-id="uvod">Uvod</h2>
<p>Hrvatski katolički medijski prostor predstavlja jedan od najrazvijenijih religijskih medijskih ekosustava u Europi, ukorijenjen u <strong>173 godine izdavačke povijesti</strong> i podržan vjerničkom populacijom koja čini <strong>83% nacionalnog stanovništva</strong>. Katolička Crkva u Hrvatskoj operira integriranu mrežu tiskanih, emitiranih i digitalnih medija koja seže od župnih biltena do nacionalno licencirane televizije. Ova infrastruktura oblikovana je jedinstvenom poviješću preživljavanja komunističke represije.</p>
<p>Suvremeni katolički medijski sustav centriran je oko <strong>Hrvatske katoličke mreže (HKM)</strong>, uspostavljene 2018. godine radi integracije glavnih crkvenih medijskih resursa pod jedinstvenu koordinaciju. Podržan značajnim državnim financiranjem putem vatikanskih konkordata, približno <strong>120 milijuna eura godišnje</strong> usmjereno je prema vjerskim zajednicama, od čega oko 95% prima Katolička crkva. Hrvatski katolički mediji uživaju resurse neuobičajene za religijske medije u Europi.</p>
<section id="opseg-analize" class="level3">
<h3 class="anchored" data-anchor-id="opseg-analize">Opseg analize</h3>
<p>Analiza pokriva sljedeće dimenzije katoličkog digitalnog prostora:</p>
<ol type="1">
<li><strong>Povijesni razvoj:</strong> Od 1849. do danas (173+ godina)</li>
<li><strong>Biskupijska struktura:</strong> Svih 17 biskupija s digitalnim strategijama</li>
<li><strong>Redovničke zajednice:</strong> Muške i ženske zajednice s medijskim aktivnostima</li>
<li><strong>Akademski mediji:</strong> Teološki časopisi s međunarodnom indeksacijom</li>
<li><strong>Pastoral mladih:</strong> SHKM, FRAMA, skauti i digitalne inicijative</li>
<li><strong>Dijaspora:</strong> 189 misija u 35+ zemalja</li>
<li><strong>Digitalna transformacija:</strong> Utjecaj na tradicionalne medije i komunikaciju</li>
</ol>
<hr>
</section>
</section>
<section id="povijesni-temelji" class="level2">
<h2 class="anchored" data-anchor-id="povijesni-temelji">Povijesni temelji</h2>
<section id="od-prvih-izdanja-do-komunističke-represije-1849.1945." class="level3">
<h3 class="anchored" data-anchor-id="od-prvih-izdanja-do-komunističke-represije-1849.1945.">Od prvih izdanja do komunističke represije (1849.–1945.)</h3>
<p>Katoličko izdavaštvo u Hrvatskoj započinje <strong>1849. godine</strong> pokretanjem <em>Katoličkog lista</em> pod okriljem Zagrebačke nadbiskupije. Prvi hrvatski katolički kongres 1900. godine katalizirao je ekspanziju, uspostavljanjem Hrvatskog katoličkog tiskarskog društva i pokretanjem utjecajnih publikacija uključujući <em>Hrvatsku stražu</em> (1903.) i studentski časopis <em>Luč</em> (1905.).</p>
<p>Biskup <strong>Antun Mahnić</strong> iz Krka pojavio se kao pionirska figura, uspostavivši vlastitu tiskaru 1899. i prepoznavši da katolički tisak ima <em>odlučujuću ulogu u utjecaju na kulturu i društvo</em>. Hrvatski katolički pokret koji je uslijedio predstavljao je organizirani napor katoličkih laika za obranu i promicanje katoličkih vrijednosti u javnom životu, stvarajući institucionalne preduvjete za kasniji razvoj katoličkih medija.</p>
<section id="kronologija-ranog-razdoblja" class="level4">
<h4 class="anchored" data-anchor-id="kronologija-ranog-razdoblja">Kronologija ranog razdoblja</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 36%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Godina</th>
<th>Događaj</th>
<th>Značaj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1849</td>
<td>Pokretanje <em>Katoličkog lista</em></td>
<td>Prvi katolički periodički tisak</td>
</tr>
<tr class="even">
<td>1899</td>
<td>Mahnićeva tiskara na Krku</td>
<td>Pionirski izdavački pothvat</td>
</tr>
<tr class="odd">
<td>1900</td>
<td>Prvi hrvatski katolički kongres</td>
<td>Institucionalizacija pokreta</td>
</tr>
<tr class="even">
<td>1903</td>
<td><em>Hrvatska straža</em></td>
<td>Politički angažiran katolički tisak</td>
</tr>
<tr class="odd">
<td>1905</td>
<td>Časopis <em>Luč</em></td>
<td>Studentski katolički pokret</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="otpor-i-opstanak-u-jugoslavenskom-razdoblju-1945.1991." class="level3">
<h3 class="anchored" data-anchor-id="otpor-i-opstanak-u-jugoslavenskom-razdoblju-1945.1991.">Otpor i opstanak u jugoslavenskom razdoblju (1945.–1991.)</h3>
<p>Komunističko jugoslavensko razdoblje (1945.–1991.) predstavljalo je najtamnije i ujedno najdefinirajuće razdoblje za hrvatske katoličke medije. Gotovo sve katoličke publikacije pale su pod kontrolu Komunističke partije, katoličke škole su zatvorene, a Katolički bogoslovni fakultet izbačen je sa Sveučilišta u Zagrebu 1952. godine.</p>
<p>Protiv ove represije, osnivanje <strong>Glasa Koncila</strong> 4. listopada 1962. postalo je prekretnica. Započevši kao umnoženi bilten koji je izvještavao o Drugom vatikanskom koncilu, pod urednicima poput legendarnog <strong>Živka Kustića</strong> (koji je zatvoren 1985. zbog <em>širenja dezinformacija</em>), <em>Glas Koncila</em> izrastao je u jedine katoličke novine u Jugoslaviji koje nisu bile pod kontrolom Komunističke partije. Tijekom 1970-ih, <em>Glas Koncila</em> dosegao je nakladu od približno <strong>140.000 primjeraka tjedno</strong>, čineći ga najčitanijim katoličkim periodom u cijeloj Jugoslaviji i simbolom otpora komunističkoj cenzuri.</p>
<p>Ovo iskustvo otpora oblikovalo je identitet katoličkih medija kao glasa alternativnog javnog prostora, što ostaje relevantno za razumijevanje suvremene pozicije katoličkih medija u hrvatskom društvu.</p>
</section>
<section id="ekspanzija-nakon-neovisnosti-1991.2018." class="level3">
<h3 class="anchored" data-anchor-id="ekspanzija-nakon-neovisnosti-1991.2018.">Ekspanzija nakon neovisnosti (1991.–2018.)</h3>
<p>Neovisnost 1991. pokrenula je brzi razvoj katoličkih medija:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 34%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Godina</th>
<th>Događaj</th>
<th>Utjecaj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1993. (svibanj)</td>
<td>Formalno uspostavljanje Hrvatske biskupske konferencije</td>
<td>Institucionalna koordinacija</td>
</tr>
<tr class="even">
<td>1993. (travanj)</td>
<td>Osnivanje Informativne katoličke agencije (IKA)</td>
<td>Profesionalno novinarstvo</td>
</tr>
<tr class="odd">
<td>1997. (svibanj)</td>
<td>Početak emitiranja Hrvatskog katoličkog radija (HKR)</td>
<td>Nacionalna radio mreža</td>
</tr>
<tr class="even">
<td>2015. (Božić)</td>
<td>Lansiranje Laudato TV-a</td>
<td>Televizijska prisutnost</td>
</tr>
<tr class="odd">
<td>2018.</td>
<td>Uspostava Hrvatske katoličke mreže (HKM)</td>
<td>Digitalna integracija</td>
</tr>
<tr class="even">
<td>2019.</td>
<td>Laudato TV najgledanija lokalna televizija</td>
<td>Mainstream uspjeh</td>
</tr>
<tr class="odd">
<td>2021.</td>
<td>Novi studijski kompleks Laudato TV (1.300 m²)</td>
<td>Infrastrukturni razvoj</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="suvremena-medijska-infrastruktura" class="level2">
<h2 class="anchored" data-anchor-id="suvremena-medijska-infrastruktura">Suvremena medijska infrastruktura</h2>
<section id="hrvatska-katolička-mreža-kao-integracijska-platforma" class="level3">
<h3 class="anchored" data-anchor-id="hrvatska-katolička-mreža-kao-integracijska-platforma">Hrvatska katolička mreža kao integracijska platforma</h3>
<p>Suvremeni katolički medijski ekosustav operira kroz nekoliko međusobno povezanih kanala pod općom koordinacijom Hrvatske biskupske konferencije (HBK). <strong>Hrvatska katolička mreža (HKM)</strong>, pod vodstvom ravnatelja doc. dr. Krunoslava Novaka (od 2022.), služi kao integrirana platforma koja kombinira IKA novinske usluge i Hrvatski katolički radio, s jedinstvenom web prisutnošću na hkm.hr.</p>
<section id="najvažnije-platforme-katoličkog-medijskog-ekosustava" class="level4">
<h4 class="anchored" data-anchor-id="najvažnije-platforme-katoličkog-medijskog-ekosustava">Najvažnije platforme katoličkog medijskog ekosustava</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 12%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>Platforma</th>
<th>Tip</th>
<th>Ključne karakteristike</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>hkm.hr</strong></td>
<td>Web portal</td>
<td>Krovni portal HBK-a, integrira IKA vijesti i HKR sadržaj</td>
</tr>
<tr class="even">
<td><strong>ika.hkm.hr</strong></td>
<td>Novinska agencija</td>
<td>Službena katolička agencija, ~50 vijesti dnevno, 40+ novinara</td>
</tr>
<tr class="odd">
<td><strong>bitno.net</strong></td>
<td>Web portal</td>
<td>Nezavisni portal, ~2,35 milijuna posjeta godišnje (2012.)</td>
</tr>
<tr class="even">
<td><strong>laudato.hr</strong></td>
<td>TV + streaming</td>
<td>EWTN afilijat, najgledanija lokalna TV (2019.)</td>
</tr>
<tr class="odd">
<td><strong>HKR</strong></td>
<td>Radio</td>
<td>1,5 milijuna redovitih slušatelja, 95% pokrivenost</td>
</tr>
<tr class="even">
<td><strong>glas-koncila.hr</strong></td>
<td>Tjednik + web</td>
<td>Najstarije katoličke novine, kontinuirano od 1962.</td>
</tr>
<tr class="odd">
<td><strong>radiomarija.hr</strong></td>
<td>Radio</td>
<td>Mreža frekvencija, streaming, aplikacija</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="emitiranje-kao-okosnica-komunikacije" class="level3">
<h3 class="anchored" data-anchor-id="emitiranje-kao-okosnica-komunikacije">Emitiranje kao okosnica komunikacije</h3>
<p>Za razliku od digitalno-nativnih medijskih ekosustava, hrvatski katolički medijski prostor ostaje <strong>izrazito radio-centriran</strong>. Hrvatski katolički radio, osnovan 17. svibnja 1997. blagoslovom kardinala Kuharića, operira pod nacionalnom koncesijom s pokrivenošću od 95% hrvatskog teritorija. S procijenjenih <strong>1,5 milijuna redovitih slušatelja</strong> u dobi od 30 do 60 godina, HKR predstavlja najznačajniju katoličku medijsku platformu u zemlji po dosegu publike.</p>
<p><strong>Laudato TV</strong>, lansiran na Božić 2015. i vođen od strane Ksenije Abramović, operira kao EWTN afilijat sa studijima u Zagrebu, Splitu i drugim gradovima. U svibnju 2021., kardinal Josip Bozanić blagoslovio je novi studijski kompleks od 1.300 četvornih metara. Programska ponuda uključuje:</p>
<ul>
<li>Dnevne prijenose mise (7:00 iz Nacionalnog svetišta sv. Josipa ili Svetišta Majke Božje Remetske)</li>
<li>Izvještavanje iz Vatikana</li>
<li>Vijesti iz Svete zemlje (jedinstveno među hrvatskim televizijama)</li>
<li>Obiteljski i katehizacijski sadržaj</li>
<li>Emisija <strong>“Generacija+”</strong> za mlade</li>
</ul>
</section>
<section id="izdavačka-infrastruktura" class="level3">
<h3 class="anchored" data-anchor-id="izdavačka-infrastruktura">Izdavačka infrastruktura</h3>
<p><strong>Kršćanska sadašnjost</strong>, osnovana 1968. dekretom nadbiskupa kardinala Franje Šepera, operira kao najveći crkveni izdavač u Hrvatskoj. Vlasnik približno 40 knjižnih serija i 6 periodičnih publikacija, ovaj izdavač u vlasništvu Zagrebačke nadbiskupije proizvodi liturgijske knjige, biblijsku literaturu, teološka djela i obiteljski časopis <em>Kana</em>. <strong>Verbum</strong> u Splitu objavio je preko 800 naslova i operira 11-13 knjižara diljem zemlje, pozicionirajući se kao <em>hrvatska knjižara za cijelu obitelj</em>.</p>
</section>
</section>
</section>
<section id="ii.-dio-biskupijska-struktura" class="level1">
<h1>II. DIO: BISKUPIJSKA STRUKTURA</h1>
<section id="metropolitanske-nadbiskupije" class="level2">
<h2 class="anchored" data-anchor-id="metropolitanske-nadbiskupije">Metropolitanske nadbiskupije</h2>
<p>Četiri metropolitanske nadbiskupije — Zagrebačka, Splitsko-makarska, Đakovačko-osječka i Riječka — čine okosnicu katoličkog digitalnog prostora u Hrvatskoj.</p>
<section id="zagrebačka-nadbiskupija" class="level3">
<h3 class="anchored" data-anchor-id="zagrebačka-nadbiskupija">Zagrebačka nadbiskupija</h3>
<p>Zagrebačka nadbiskupija, pod vodstvom nadbiskupa Dražena Kutleše koji ujedno predsjeda HBK, predstavlja središnju instituciju hrvatskog katolicizma. Digitalna prisutnost uključuje:</p>
<ul>
<li><p><strong>Web portal:</strong> zg-nadbiskupija.hr s vijestima i pastoralnim kalendarom</p></li>
<li><p><strong>Instagram:</strong> <span class="citation" data-cites="zgnadbiskupija">@zgnadbiskupija</span> (2.325 pratitelja, 2.704 objave)</p></li>
<li><p><strong>YouTube:</strong> Kanal sa 151 videom (666 pretplatnika, 191.410 pregleda)</p></li>
<li><p><strong>Facebook:</strong> Prva biskupija na platformi (aktivan od 2013. godine)</p></li>
</ul>
<p>Nadbiskupija koordinira <strong>50+ redovničkih zajednica</strong> na svom području, uključujući franjevce, dominikance, isusovce i karmelićane. Ured za pastoral mladih “Ivan Pavao II.” (mladicentar.org) vodi programe za mlade s aktivnom Instagram prisutnošću.</p>
</section>
<section id="splitsko-makarska-nadbiskupija" class="level3">
<h3 class="anchored" data-anchor-id="splitsko-makarska-nadbiskupija">Splitsko-makarska nadbiskupija</h3>
<p>Splitsko-makarska nadbiskupija razvila je <strong>mrežu župnih medijskih suradnika</strong> kroz formativne susrete pokrenute 2025. godine. Nadbiskup Zdenko Križić vodi ovu drugu najveću hrvatsku nadbiskupiju.</p>
<ul>
<li><strong>Web portal:</strong> smn.hr s vijestima i dokumentima</li>
<li><strong>Instagram:</strong> <span class="citation" data-cites="smnadbiskupija">@smnadbiskupija</span> (~950 pratitelja)</li>
<li><strong>YouTube:</strong> Aktivni kanal s prijenosima</li>
<li><strong>Župni suradnici:</strong> Mreža medijski educiranih laika</li>
</ul>
</section>
<section id="đakovačko-osječka-nadbiskupija" class="level3">
<h3 class="anchored" data-anchor-id="đakovačko-osječka-nadbiskupija">Đakovačko-osječka nadbiskupija</h3>
<p>Đakovačko-osječka nadbiskupija posjeduje jedinstveni <strong>digitalizirani arhiv Vjesnika biskupije od 1873. do 2020.</strong> — najopsežniji digitalni arhiv crkvene periodike u Hrvatskoj.</p>
<ul>
<li><strong>Vjesnik biskupije:</strong> 150+ godina digitalizirano</li>
<li><strong>Web portal:</strong> djos.hr</li>
<li><strong>Akademska suradnja:</strong> Institut Ivo Pilar proveo studiju o digitalnoj prisutnosti Crkve tijekom pandemije</li>
</ul>
</section>
<section id="riječka-nadbiskupija" class="level3">
<h3 class="anchored" data-anchor-id="riječka-nadbiskupija">Riječka nadbiskupija</h3>
<p><strong>Riječka nadbiskupija bila je prva u Hrvatskoj prisutna na društvenim mrežama</strong>, demonstrirajući rani digitalni pionirski duh.</p>
<hr>
</section>
</section>
<section id="sufraganske-biskupije" class="level2">
<h2 class="anchored" data-anchor-id="sufraganske-biskupije">Sufraganske biskupije</h2>
<p>Od 13 sufraganskih biskupija i eparhija, digitalna prisutnost značajno varira, od naprednih do bazičnih implementacija.</p>
<section id="biskupije-s-najsnažnijom-digitalnom-prisutnošću" class="level3">
<h3 class="anchored" data-anchor-id="biskupije-s-najsnažnijom-digitalnom-prisutnošću">Biskupije s najsnažnijom digitalnom prisutnošću</h3>
<section id="požeška-biskupija" class="level4">
<h4 class="anchored" data-anchor-id="požeška-biskupija">Požeška biskupija</h4>
<p><strong>Požeška biskupija demonstrira najsnažniju digitalnu prisutnost</strong> među sufraganskim biskupijama:</p>
<ul>
<li><strong>Instagram:</strong> <span class="citation" data-cites="pozeska_biskupija">@pozeska_biskupija</span> (1.112 pratitelja)</li>
<li><strong>YouTube:</strong> Svakodnevni prijenosi misa</li>
<li><strong>Glasilo:</strong> “Zajedništvo” digitalno dostupno</li>
<li><strong>SHKM 2026:</strong> Domaćin sljedećeg Susreta (shkm2026.hr)</li>
</ul>
</section>
<section id="krčka-biskupija" class="level4">
<h4 class="anchored" data-anchor-id="krčka-biskupija">Krčka biskupija</h4>
<p>Krčka biskupija osigurava <strong>svakodnevne livestream prijenose</strong> iz katedrale:</p>
<ul>
<li><strong>Prijenos:</strong> 8:00 i 18:00 sati</li>
<li><strong>Platforma:</strong> biskupijakrk.hr/livestream</li>
<li><strong>YouTube:</strong> Aktivni arhiv prijenosa</li>
</ul>
</section>
<section id="dubrovačka-biskupija" class="level4">
<h4 class="anchored" data-anchor-id="dubrovačka-biskupija">Dubrovačka biskupija</h4>
<p>Dubrovačka biskupija razvila je jedinstven <strong>“Biskupov blog”</strong> s razmišljanjima uz nedjelje i blagdane:</p>
<ul>
<li><strong>Portal:</strong> db.hr</li>
<li><strong>Blog:</strong> Osobna razmišljanja biskupa</li>
<li><strong>Uredi:</strong> Digitalno koordinirani pastoralni uredi</li>
</ul>
</section>
<section id="varaždinska-biskupija" class="level4">
<h4 class="anchored" data-anchor-id="varaždinska-biskupija">Varaždinska biskupija</h4>
<ul>
<li><strong>Mladi:</strong> <span class="citation" data-cites="mladi.varazdinske.biskupije">@mladi.varazdinske.biskupije</span> (1.271 pratitelja)</li>
<li><strong>Web:</strong> varazdinska-biskupija.hr</li>
<li><strong>Pastoral:</strong> Aktivni programi za mlade</li>
</ul>
</section>
</section>
<section id="kompletni-pregled-digitalnih-kapaciteta-svih-biskupija" class="level3">
<h3 class="anchored" data-anchor-id="kompletni-pregled-digitalnih-kapaciteta-svih-biskupija">Kompletni pregled digitalnih kapaciteta svih biskupija</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Biskupija</th>
<th>Web</th>
<th>Instagram</th>
<th>YouTube</th>
<th>Facebook</th>
<th>Livestream</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zagrebačka</td>
<td>✓</td>
<td>2.325</td>
<td>666</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td>Splitsko-makarska</td>
<td>✓</td>
<td>~950</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Đakovačko-osječka</td>
<td>✓</td>
<td>—</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td>Riječka</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Zadarska</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td>Požeška</td>
<td>✓</td>
<td>1.112</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Krčka</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>2x/dan</td>
</tr>
<tr class="even">
<td>Dubrovačka</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Varaždinska</td>
<td>✓</td>
<td>1.271*</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td>Gospićko-senjska</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Šibenska</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td>Hvarska</td>
<td>✓</td>
<td>—</td>
<td>—</td>
<td>✓</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Bjelovarsko-križevačka</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td>Sisačka</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Porečko-pulska</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td>Križevačka eparhija</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Vojni ordinarijat</td>
<td>✓✓</td>
<td>—</td>
<td>—</td>
<td>✓</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><em>Napomena: Varaždinska ima profil <span class="citation" data-cites="mladi.varazdinske.biskupije">@mladi.varazdinske.biskupije</span></em></p>
<hr>
</section>
</section>
</section>
<section id="iii.-dio-redovničke-zajednice" class="level1">
<h1>III. DIO: REDOVNIČKE ZAJEDNICE</h1>
<p>Hrvatska broji desetke muških i ženskih redovničkih zajednica s bogatom tradicijom tiskanih i digitalnih medija. Centralni portal <strong>redovnistvo.hr</strong> okuplja sve zajednice pod okriljem Hrvatske redovničke konferencije.</p>
<section id="franjevačke-zajednice" class="level2">
<h2 class="anchored" data-anchor-id="franjevačke-zajednice">Franjevačke zajednice</h2>
<p>Tri franjevačke provincije djeluju u Hrvatskoj, čineći najbrojniju redovničku obitelj:</p>
<section id="provincija-presvetog-otkupitelja-ofm-split" class="level3">
<h3 class="anchored" data-anchor-id="provincija-presvetog-otkupitelja-ofm-split">Provincija Presvetog Otkupitelja (OFM, Split)</h3>
<p><strong>Najbrojnija muška redovnička zajednica</strong> u Splitsko-makarskoj nadbiskupiji:</p>
<ul>
<li><strong>Časopisi:</strong> Marija, Služba Božja, Kačić, Panis Vitae</li>
<li><strong>Portal:</strong> ofm.hr</li>
<li><strong>FRAMA:</strong> Koordinacija franjevačke mladeži</li>
<li><strong>Samostani:</strong> 30+ lokacija u Dalmaciji i Hercegovini</li>
</ul>
</section>
<section id="franjevci-konventualci-ofmconv" class="level3">
<h3 class="anchored" data-anchor-id="franjevci-konventualci-ofmconv">Franjevci konventualci (OFMConv)</h3>
<p>Od 1999. izdaju <strong>časopis Veritas</strong> (veritas.hr):</p>
<ul>
<li><strong>Naklada:</strong> ~7.000 primjeraka</li>
<li><strong>Web knjižara:</strong> Online prodaja publikacija</li>
<li><strong>Samostani:</strong> Zagreb (Sv. Antun), Šibenik, Pula</li>
</ul>
</section>
<section id="kapucini-ofmcap" class="level3">
<h3 class="anchored" data-anchor-id="kapucini-ofmcap">Kapucini (OFMCap)</h3>
<ul>
<li><strong>Blog:</strong> “Ljudima prijatelj”</li>
<li><strong>Portal:</strong> padrepio.hr (posvećen sv. Padre Piju)</li>
<li><strong>Samostani:</strong> Zagreb, Split, Rijeka</li>
</ul>
</section>
</section>
<section id="isusovci-družba-isusova" class="level2">
<h2 class="anchored" data-anchor-id="isusovci-družba-isusova">Isusovci (Družba Isusova)</h2>
<p>Isusovci putem Filozofsko-teološkog instituta izdaju časopis <strong>Obnovljeni život</strong> od 1919. godine — jedan od najstarijih aktivnih znanstvenih časopisa u Hrvatskoj. Obnovljeni život slavi <strong>105+ godina kontinuiranog izlaženja</strong> (1919.-2025.), čineći ga jednim od najdugotrajnijih akademskih časopisa u Hrvatskoj.</p>
<ul>
<li><strong>HRCAK:</strong> Besplatan pristup svim brojevima</li>
<li><strong>SKAC:</strong> Studentski katolički centar</li>
<li><strong>Gimnazija:</strong> Isusovačka klasična gimnazija Osijek</li>
<li><strong>Duhovne vježbe:</strong> ignacije.hr (2-6 mjeseci formati)</li>
<li><strong>Portal:</strong> isusovci.hr</li>
</ul>
</section>
<section id="dominikanci" class="level2">
<h2 class="anchored" data-anchor-id="dominikanci">Dominikanci</h2>
<p><strong>Dominikanci prednjače u multiplatformskoj prisutnosti</strong>, između ostalog su i jedinstveni primjer katoličke zajednice na TikToku u Hrvatskoj.</p>
</section>
<section id="salezijanci" class="level2">
<h2 class="anchored" data-anchor-id="salezijanci">Salezijanci</h2>
<p>Salezijanci putem <strong>donbosco.hr</strong> nude duhovne sadržaje i oratorije za mlade:</p>
<ul>
<li><strong>Mjesečnik:</strong> “Don Bosco danas”</li>
<li><strong>Nova Eva:</strong> YouTube kanal (~43.700 pretplatnika, 12 milijuna pregleda)</li>
<li><strong>Oratoriji:</strong> Programi za djecu i mlade</li>
<li><strong>Ključne figure:</strong> Don Damir Stojić, Don Tomislav Lukač</li>
</ul>
</section>
<section id="benediktinci-i-trapisti" class="level2">
<h2 class="anchored" data-anchor-id="benediktinci-i-trapisti">Benediktinci i trapisti</h2>
<ul>
<li><strong>Benediktinci Pašman:</strong> samostan-cokovac.hr (jedini aktivni muški benediktinski samostan)</li>
<li><strong>Trapisti Banja Luka:</strong> Nekada 230 članova, danas samo 2 redovnika</li>
</ul>
<hr>
</section>
</section>
<section id="iv.-dio-akademski-katolički-mediji" class="level1">
<h1>IV. DIO: AKADEMSKI KATOLIČKI MEDIJI</h1>
<p>Hrvatski teološki časopisi postižu značajnu međunarodnu vidljivost kroz indeksaciju u prestižnim bazama podataka.</p>
<section id="časopisi-s-međunarodnom-indeksacijom" class="level2">
<h2 class="anchored" data-anchor-id="časopisi-s-međunarodnom-indeksacijom">Časopisi s međunarodnom indeksacijom</h2>
<section id="bogoslovska-smotra" class="level3">
<h3 class="anchored" data-anchor-id="bogoslovska-smotra">Bogoslovska smotra</h3>
<p><strong>Bogoslovska smotra</strong> (ISSN 0352-3101), pokrenuta 1910. na Katoličkom bogoslovnom fakultetu u Zagrebu, jedini je hrvatski teološki časopis indeksiran u <strong>Web of Science Core Collection (ESCI)</strong> i <strong>Journal Citation Reports</strong>. Bogoslovska smotra jedini je hrvatski teološki časopis s JCR faktorom utjecaja, što ga pozicionira među vodeće teološke publikacije u regiji.</p>
<ul>
<li><strong>Izlaženje:</strong> 5 brojeva godišnje</li>
<li><strong>DOI:</strong> Svi članci imaju identifikatore</li>
<li><strong>Licenca:</strong> CC BY-NC 4.0 otvoreni pristup</li>
<li><strong>HRCAK:</strong> Potpuni arhiv dostupan</li>
<li><strong>Godina osnivanja:</strong> 1910.</li>
</ul>
</section>
<section id="obnovljeni-život" class="level3">
<h3 class="anchored" data-anchor-id="obnovljeni-život">Obnovljeni život</h3>
<p><strong>Obnovljeni život</strong> (ISSN 0351-3947) isusovačkog Filozofsko-teološkog instituta:</p>
<ul>
<li><strong>Osnovan:</strong> 1919. (105+ godina)</li>
<li><strong>Indeksacija:</strong> SCOPUS, ERIH PLUS</li>
<li><strong>Pristup:</strong> Besplatan na HRCAK-u</li>
<li><strong>Fokus:</strong> Filozofija, teologija, duhovnost</li>
</ul>
</section>
<section id="crkva-u-svijetu" class="level3">
<h3 class="anchored" data-anchor-id="crkva-u-svijetu">Crkva u svijetu</h3>
<p><strong>Crkva u svijetu</strong> (ISSN 0352-4000) iz Splita:</p>
<ul>
<li><strong>Kategorija:</strong> A1</li>
<li><strong>Izlaženje:</strong> 4 broja godišnje od 1966.</li>
<li><strong>Indeksacija:</strong> SCOPUS</li>
<li><strong>Izdavač:</strong> Katolički bogoslovni fakultet Split</li>
</ul>
</section>
<section id="diacovensia" class="level3">
<h3 class="anchored" data-anchor-id="diacovensia">Diacovensia</h3>
<p><strong>Diacovensia</strong> (ISSN 1330-2655) iz Đakova:</p>
<ul>
<li><strong>Kategorija:</strong> A1 (od 2017.)</li>
<li><strong>Indeksacija:</strong> SCOPUS</li>
<li><strong>Fokus:</strong> Teologija i društvene teme</li>
<li><strong>Izdavač:</strong> Katolički bogoslovni fakultet Đakovo</li>
</ul>
</section>
<section id="pregled-svih-akademskih-časopisa" class="level3">
<h3 class="anchored" data-anchor-id="pregled-svih-akademskih-časopisa">Pregled svih akademskih časopisa</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Časopis</th>
<th>God. osn.</th>
<th>WoS</th>
<th>SCOPUS</th>
<th>ERIH+</th>
<th>HRCAK</th>
<th>Kategorija</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bogoslovska smotra</td>
<td>1910</td>
<td>✓ ESCI/JCR</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>A1</td>
</tr>
<tr class="even">
<td>Obnovljeni život</td>
<td>1919</td>
<td>—</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>A1</td>
</tr>
<tr class="odd">
<td>Crkva u svijetu</td>
<td>1966</td>
<td>—</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>A1</td>
</tr>
<tr class="even">
<td>Diacovensia</td>
<td>1993</td>
<td>—</td>
<td>✓</td>
<td>✓</td>
<td>✓</td>
<td>A1</td>
</tr>
<tr class="odd">
<td>Služba Božja</td>
<td>1960</td>
<td>—</td>
<td>—</td>
<td>✓</td>
<td>✓</td>
<td>A2</td>
</tr>
<tr class="even">
<td>Riječki teološki časopis</td>
<td>1993</td>
<td>—</td>
<td>—</td>
<td>✓</td>
<td>✓</td>
<td>A2</td>
</tr>
<tr class="odd">
<td>Croatica Christiana Periodica</td>
<td>1977</td>
<td>—</td>
<td>—</td>
<td>✓</td>
<td>✓</td>
<td>A1</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="hrvatsko-katoličko-sveučilište" class="level2">
<h2 class="anchored" data-anchor-id="hrvatsko-katoličko-sveučilište">Hrvatsko katoličko sveučilište</h2>
<p><strong>Hrvatsko katoličko sveučilište</strong> (unicath.hr), osnovano 2006., razvija značajnu digitalnu prisutnost:</p>
<ul>
<li><strong>Instagram:</strong> <span class="citation" data-cites="unicath.hr">@unicath.hr</span> (3.381 pratitelja)</li>
<li><strong>TikTok:</strong> <span class="citation" data-cites="unicath.hr">@unicath.hr</span> (jedina institucija na TikToku)</li>
<li><strong>Pristup:</strong> HRCAK, DOAJ, PERO portal</li>
<li><strong>Odjeli:</strong> Komunikologija, sociologija, povijest, psihologija, pravo, računarstvo</li>
<li><strong>Projekt:</strong> DigiKat (2025.-2027.)</li>
</ul>
</section>
<section id="katolički-bogoslovni-fakultet-zagreb" class="level2">
<h2 class="anchored" data-anchor-id="katolički-bogoslovni-fakultet-zagreb">Katolički bogoslovni fakultet Zagreb</h2>
<ul>
<li><strong>Teološka kultura:</strong> Program cjeloživotnog obrazovanja s online komponentama</li>
<li><strong>Teološko-pastoralni tjedan:</strong> Dostupan na YouTube kanalu</li>
<li><strong>Bogoslovska smotra:</strong> Vodeći teološki časopis</li>
</ul>
<hr>
</section>
</section>
<section id="v.-dio-pastoral-mladih" class="level1">
<h1>V. DIO: PASTORAL MLADIH</h1>
<p>Pastoral mladih gradi sofisticiranu digitalnu infrastrukturu za dosezanje nove generacije vjernika.</p>
<section id="susret-hrvatske-katoličke-mladeži-shkm" class="level2">
<h2 class="anchored" data-anchor-id="susret-hrvatske-katoličke-mladeži-shkm">Susret hrvatske katoličke mladeži (SHKM)</h2>
<p><strong>SHKM</strong> od 1996. okuplja 5.000-50.000 mladih svake dvije godine.</p>
<section id="shkm-2026-digitalna-infrastruktura" class="level3">
<h3 class="anchored" data-anchor-id="shkm-2026-digitalna-infrastruktura">SHKM 2026 digitalna infrastruktura</h3>
<p>SHKM 2026 u Požegi ima profesionalnu digitalnu prisutnost:</p>
<ul>
<li><strong>Web:</strong> shkm2026.hr</li>
<li><strong>Facebook:</strong> Aktivna stranica</li>
<li><strong>Instagram:</strong> <span class="citation" data-cites="shkm2026">@shkm2026</span></li>
<li><strong>TikTok:</strong> Prisutnost za mlade</li>
<li><strong>SHKM kvizaška liga:</strong> Zoom s 74 ekipe</li>
<li><strong>Prijave:</strong> E-župe platforma</li>
</ul>
</section>
</section>
<section id="frama-franjevačka-mladež" class="level2">
<h2 class="anchored" data-anchor-id="frama-franjevačka-mladež">FRAMA (Franjevačka mladež)</h2>
<p><strong>FRAMA</strong>, osnovana 1992., okuplja 1.500-2.000 članova u 70-ak bratstava:</p>
<ul>
<li><strong>Portal:</strong> frama-portal.ofs.hr</li>
<li><strong>YouTube:</strong> Aktivni kanal</li>
<li><strong>Formacija:</strong> “Pismo duši” program</li>
<li><strong>Članstvo:</strong> 1.500-2.000 mladih</li>
</ul>
</section>
<section id="katolički-skauti-hrvatske" class="level2">
<h2 class="anchored" data-anchor-id="katolički-skauti-hrvatske">Katolički skauti Hrvatske</h2>
<ul>
<li><strong>Osnivanje:</strong> 2002. u Rijeci</li>
<li><strong>Prisutnost:</strong> 8-9 biskupija</li>
<li><strong>Centar:</strong> “Bl. Alojzije Stepinac” Drivenik</li>
<li><strong>Članstvo:</strong> UIGSE-FSE (međunarodna federacija)</li>
</ul>
</section>
<section id="taizé-zajednica" class="level2">
<h2 class="anchored" data-anchor-id="taizé-zajednica">Taizé zajednica</h2>
<ul>
<li><strong>Zagreb 2006/07:</strong> 29. Europski susret s 40.000 sudionika</li>
<li><strong>Koordinacija:</strong> Putem župnih zajednica</li>
<li><strong>Online:</strong> Prijenosi molitava</li>
</ul>
</section>
<section id="medijski-programi-za-mlade" class="level2">
<h2 class="anchored" data-anchor-id="medijski-programi-za-mlade">Medijski programi za mlade</h2>
<section id="laudato-tv-generacija" class="level3">
<h3 class="anchored" data-anchor-id="laudato-tv-generacija">Laudato TV — Generacija+</h3>
<p>Emisija <strong>“Generacija+”</strong> na Laudato TV okuplja mlade voditelje:</p>
<ul>
<li><strong>Format:</strong> Talk show s mladima</li>
<li><strong>Teme:</strong> Vjera, društvo, aktualna pitanja</li>
<li><strong>Doseg:</strong> 48.000+ Instagram pratitelja (<span class="citation" data-cites="laudatotv">@laudatotv</span>)</li>
</ul>
</section>
<section id="hrvatski-katolički-radio" class="level3">
<h3 class="anchored" data-anchor-id="hrvatski-katolički-radio">Hrvatski katolički radio</h3>
<ul>
<li><strong>“Budimo mladi”:</strong> Emisija za mlade</li>
<li><strong>“Oni rokaju za Gospodina”:</strong> Glazbeni program</li>
<li><strong>Streaming:</strong> hkr.hkm.hr</li>
</ul>
<hr>
</section>
</section>
</section>
<section id="vi.-dio-hrvatska-katolička-dijaspora" class="level1">
<h1>VI. DIO: HRVATSKA KATOLIČKA DIJASPORA</h1>
<p>Hrvatska katolička dijaspora organizirana je u <strong>189 župa, misija i centara</strong> diljem svijeta.</p>
<section id="globalna-struktura" class="level2">
<h2 class="anchored" data-anchor-id="globalna-struktura">Globalna struktura</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regija</th>
<th>Broj misija</th>
<th>Ključne lokacije</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Njemačka</td>
<td>96-99</td>
<td>Berlin, München, Frankfurt, Stuttgart</td>
</tr>
<tr class="even">
<td>Kanada</td>
<td>17</td>
<td>Toronto, Vancouver, Calgary</td>
</tr>
<tr class="odd">
<td>SAD</td>
<td>16</td>
<td>Chicago, New York, Los Angeles</td>
</tr>
<tr class="even">
<td>Australija</td>
<td>14</td>
<td>Sydney, Melbourne, Perth</td>
</tr>
<tr class="odd">
<td>Švicarska</td>
<td>12</td>
<td>Zürich, Basel, Bern</td>
</tr>
<tr class="even">
<td>Austrija</td>
<td>8</td>
<td>Beč, Graz, Salzburg</td>
</tr>
<tr class="odd">
<td>Ostale</td>
<td>42+</td>
<td>Argentina, Čile, Novi Zeland…</td>
</tr>
</tbody>
</table>
<section id="pastoralno-osoblje" class="level3">
<h3 class="anchored" data-anchor-id="pastoralno-osoblje">Pastoralno osoblje</h3>
<ul>
<li><strong>Svećenici:</strong> 197 (63 dijecezanska, 134 redovnička)</li>
<li><strong>Redovnice:</strong> 50</li>
<li><strong>Pastoralni suradnici:</strong> 43</li>
</ul>
</section>
</section>
<section id="digitalna-prisutnost-dijaspore" class="level2">
<h2 class="anchored" data-anchor-id="digitalna-prisutnost-dijaspore">Digitalna prisutnost dijaspore</h2>
<section id="njemačka" class="level3">
<h3 class="anchored" data-anchor-id="njemačka">Njemačka</h3>
<ul>
<li><strong>Portal:</strong> zivazajednica.de (koordinacija 96-99 misija)</li>
<li><strong>HKŽ München:</strong> YouTube livestream od 2020.</li>
<li><strong>HKM Berlin:</strong> hkm.hr/berlin s prijenosima</li>
</ul>
</section>
<section id="švicarska" class="level3">
<h3 class="anchored" data-anchor-id="švicarska">Švicarska</h3>
<ul>
<li><strong>Portal:</strong> kroaten-missionen.ch</li>
<li><strong>Glasilo:</strong> MOVIS</li>
<li><strong>Misije:</strong> 12 aktivnih zajednica</li>
</ul>
</section>
<section id="austrija" class="level3">
<h3 class="anchored" data-anchor-id="austrija">Austrija</h3>
<ul>
<li><strong>HKM Beč:</strong> Najposjećenija crkva u Beču</li>
<li><strong>Vodstvo:</strong> Hrvatska franjevačka provincija od 1971.</li>
<li><strong>Web:</strong> hkm-wien.at</li>
</ul>
</section>
<section id="australija" class="level3">
<h3 class="anchored" data-anchor-id="australija">Australija</h3>
<ul>
<li><strong>Portal:</strong> hkc.com.au (14 centara)</li>
<li><strong>Aplikacija:</strong> Croatian Catholic Radio APP</li>
<li><strong>Centri:</strong> Sydney, Melbourne, Perth, Adelaide, Brisbane</li>
</ul>
</section>
<section id="sad" class="level3">
<h3 class="anchored" data-anchor-id="sad">SAD</h3>
<ul>
<li><strong>Chicago:</strong> Bl. Alojzije Stepinac župa</li>
<li><strong>Radio:</strong> Croatian Catholic Radio (WNDZ 750AM, subotom)</li>
<li><strong>New York:</strong> Sv. Ćiril i Metod (od 1974.)</li>
</ul>
</section>
<section id="koordinacija" class="level3">
<h3 class="anchored" data-anchor-id="koordinacija">Koordinacija</h3>
<p><strong>Ravnateljstvo dušobrižništva za Hrvate u inozemstvu</strong> pri HBK koordinira pastoralnu skrb s biskupijama podrijetla.</p>
<hr>
</section>
</section>
</section>
<section id="vii.-dio-digitalna-prisutnost" class="level1">
<h1>VII. DIO: DIGITALNA PRISUTNOST</h1>
<section id="web-portali" class="level2">
<h2 class="anchored" data-anchor-id="web-portali">Web portali</h2>
<section id="hijerarhija-digitalnih-platformi" class="level3">
<h3 class="anchored" data-anchor-id="hijerarhija-digitalnih-platformi">Hijerarhija digitalnih platformi</h3>
<div class="cell" data-fig-width="8" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    HBK[Hrvatska biskupska konferencija] --&gt; HKM[Hrvatska katolička mreža&lt;br/&gt;hkm.hr]
    HKM --&gt; IKA[IKA&lt;br/&gt;ika.hkm.hr]
    HKM --&gt; HKR[Hrvatski katolički radio&lt;br/&gt;hkr.hkm.hr]
    
    NEZAVISNI[Nezavisni akteri] --&gt; BITNO[Bitno.net&lt;br/&gt;~2.35M posjeta/god]
    NEZAVISNI --&gt; LAUDATO[Laudato TV&lt;br/&gt;laudato.hr]
    NEZAVISNI --&gt; GK[Glas Koncila&lt;br/&gt;glas-koncila.hr]
    
    BISKUPIJE[17 biskupija] --&gt; DIJECEZANSKI[Biskupijski portali]
    
    style HBK fill:#1a365d,color:#fff
    style HKM fill:#2c5282,color:#fff
    style BITNO fill:#38a169,color:#fff
    style LAUDATO fill:#38a169,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Sve <strong>17 hrvatskih biskupija</strong> (16 rimskog obreda plus jedna bizantskog obreda grkokatolička) održavaju službene web stranice s redovitim ažuriranjima:</p>
<p><strong>Metropolitanske nadbiskupije:</strong></p>
<ul>
<li>Zagreb: zg-nadbiskupija.hr</li>
<li>Split-Makarska: smn.hr</li>
<li>Đakovo-Osijek: djos.hr</li>
<li>Rijeka: ri-nadbiskupija.hr</li>
<li>Zadar: zadarskanadbiskupija.hr</li>
</ul>
</section>
</section>
<section id="društvene-mreže" class="level2">
<h2 class="anchored" data-anchor-id="društvene-mreže">Društvene mreže</h2>
<p><strong>Instagram</strong> se pojavio kao primarna platforma za katoličku digitalnu prisutnost. Analiza prisutnosti otkriva jasnu hijerarhiju između medijskih brendova, zajednica i institucionalnih računa:</p>
<section id="prisutnost-na-instagramu-verificirani-podaci" class="level3">
<h3 class="anchored" data-anchor-id="prisutnost-na-instagramu-verificirani-podaci">Prisutnost na Instagramu (verificirani podaci)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Račun</th>
<th>Pratitelji</th>
<th>Objave</th>
<th>Tip</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="laudatotv">@laudatotv</span></td>
<td><strong>48.000</strong></td>
<td>3.840</td>
<td>Televizija</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="bitnonet">@bitnonet</span></td>
<td><strong>48.000</strong></td>
<td>1.616</td>
<td>Portal</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="bozja.pobjeda">@bozja.pobjeda</span></td>
<td><strong>37.000</strong></td>
<td>Aktivan</td>
<td>Zajednica</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="hkr_hkm">@hkr_hkm</span></td>
<td><strong>24.000</strong></td>
<td>1.401</td>
<td>Radio</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="dondamirstojic">@dondamirstojic</span></td>
<td><strong>32.000+</strong></td>
<td>Aktivan</td>
<td>Svećenik</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="glas_koncila">@glas_koncila</span></td>
<td>3.486</td>
<td>2.932</td>
<td>Tjednik</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="zgnadbiskupija">@zgnadbiskupija</span></td>
<td>2.325</td>
<td>2.704</td>
<td>Institucija</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="smnadbiskupija">@smnadbiskupija</span></td>
<td>950</td>
<td>543</td>
<td>Institucija</td>
</tr>
</tbody>
</table>
<p>Značajan jaz postoji između medijskih brendova (48.000 pratitelja) i institucionalnih računa biskupija (950-2.325 pratitelja), ukazujući na nedovoljno razvijenu institucionalnu strategiju za društvene mreže.</p>
<p><strong>Twitter/X</strong> prisutnost je ograničena ali uključuje aktivne račune za HKR (<span class="citation" data-cites="hkr_radio">@hkr_radio</span> s 2.200 pratitelja) i Laudato (<span class="citation" data-cites="laudato_hr">@laudato_hr</span> s 9.085+ objava). <strong>LinkedIn</strong> prisutnost je minimalna; samo Laudato TV održava stranicu tvrtke s 199 pratitelja.</p>
</section>
</section>
<section id="youtube-i-video-sadržaj" class="level2">
<h2 class="anchored" data-anchor-id="youtube-i-video-sadržaj">YouTube i video sadržaj</h2>
<p>Video prostor otkriva jasnu podjelu između institucionalnih kanala sa skromnim praćenjem i evangelizacijski usmjerenih kanala sa znatno većom publikom:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 23%">
<col style="width: 28%">
<col style="width: 21%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Kanal</th>
<th>Pretplatnici</th>
<th>Ukupni pregledi</th>
<th>Videozapisi</th>
<th>Sadržaj</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Nova Eva</strong> (salezijanski)</td>
<td>~43.700</td>
<td>~12 milijuna</td>
<td>Opsežan</td>
<td>Kateheza, homilije</td>
</tr>
<tr class="even">
<td><strong>HKM</strong> (HBK)</td>
<td>10.900</td>
<td>2,76 milijuna</td>
<td>2.199</td>
<td>Radio programi</td>
</tr>
<tr class="odd">
<td>Zagrebačka nadbiskupija</td>
<td>666</td>
<td>191.410</td>
<td>151</td>
<td>Biskupijski događaji</td>
</tr>
<tr class="even">
<td>Laudato TV</td>
<td>~30</td>
<td>Minimalno</td>
<td>Ograničeno</td>
<td>Distribucija putem kabela</td>
</tr>
</tbody>
</table>
<p><strong>Nova Eva</strong>, koju je osnovala Hrvatska salezijanska provincija 2011., predstavlja najveći hrvatski katolički evangelizacijski YouTube kanal. Operira s približno 20 mladih kreatora sadržaja i često prikazuje istaknute svećenike poput don Damira Stojića.</p>
</section>
<section id="tiktok-kao-nova-granica" class="level2">
<h2 class="anchored" data-anchor-id="tiktok-kao-nova-granica">TikTok kao nova granica</h2>
<p>Dok katolička prisutnost na TikToku ostaje nerazvijena u usporedbi s anglofonim tržištima, Don Tomislav Lukač (<span class="citation" data-cites="dontomolukac">@dontomolukac</span>) se pojavio kao tridesetjednogodišnji salezijanski svećenik iz Kaštela s preko <strong>68.000 TikTok pratitelja</strong> i više od <strong>milijun lajkova</strong>, čineći ga najpopularnijom hrvatskom katoličkom TikTok prisutnošću. Njegov sadržaj objašnjava katoličku vjeru kroz kratke video formate koji adresiraju pop kulturu, glazbu i mladenačke teme. Trenutno studira na Papinskom teološkom institutu Ivan Pavao II. za brak i obitelj u Rimu.</p>
<p><strong>Hrvatsko katoličko sveučilište</strong> (<span class="citation" data-cites="unicath.hr">@unicath.hr</span>) održava jedinu značajnu institucionalnu TikTok prisutnost.</p>
</section>
<section id="podcasti" class="level2">
<h2 class="anchored" data-anchor-id="podcasti">Podcasti</h2>
<p>Za razliku od anglofonih tržišta gdje proliferiraju namjenske podcast platforme, hrvatski katolički audio sadržaj ostaje <strong>radio-centriran</strong>, distribuiran primarno putem tradicionalnog FM emitiranja s online streaming dopunama.</p>
<p>Identificirani namjenski podcasti:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Podcast</th>
<th>Voditelji</th>
<th>Platforma</th>
<th>Fokus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mladi za Domovinu</td>
<td>Gabrijel Lukić</td>
<td>Spotify, Apple, Google</td>
<td>Katolička mladež, nacionalni identitet</td>
</tr>
<tr class="even">
<td>Podcast Bitno.net-a</td>
<td>Anto Mikić, Ivo Džeba</td>
<td>Apple, Spotify, Podbean</td>
<td>Crkva, vjera i društvo</td>
</tr>
<tr class="odd">
<td>Povijesna četvrt</td>
<td>dr. Trpimir Vedriš</td>
<td>Višestruke platforme</td>
<td>Kontroverzne povijesne teme</td>
</tr>
<tr class="even">
<td>BP Podcast</td>
<td>Božja pobjeda</td>
<td>Višestruke platforme</td>
<td>Duhovnost, svjedočanstva</td>
</tr>
</tbody>
</table>
</section>
<section id="mobilne-aplikacije" class="level2">
<h2 class="anchored" data-anchor-id="mobilne-aplikacije">Mobilne aplikacije</h2>
<section id="službene-institucionalne-aplikacije" class="level3">
<h3 class="anchored" data-anchor-id="službene-institucionalne-aplikacije">Službene institucionalne aplikacije</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 29%">
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Aplikacija</th>
<th>Razvojni programer</th>
<th>Preuzimanja</th>
<th>Ocjena</th>
<th>Ključne značajke</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>eČasoslov</td>
<td>Kršćanska sadašnjost</td>
<td>5.000+</td>
<td>5.0/5</td>
<td>Službena Liturgija sati odobrena od HBK</td>
</tr>
<tr class="even">
<td>HKM</td>
<td>Enterwell d.o.o.</td>
<td>1.000+</td>
<td>4.8/5</td>
<td>Agregator vijesti za HKR i IKA</td>
</tr>
<tr class="odd">
<td>Grkokatolički časoslov</td>
<td>AETÓS</td>
<td>1.000+</td>
<td>5.0/5</td>
<td>Molitva bizantskog obreda</td>
</tr>
<tr class="even">
<td>Radio Marija Hrvatska</td>
<td>Radio Maria A.P.S.</td>
<td>Dostupna</td>
<td>N/A</td>
<td>Streaming i raspored programa</td>
</tr>
</tbody>
</table>
</section>
<section id="biblijske-aplikacije" class="level3">
<h3 class="anchored" data-anchor-id="biblijske-aplikacije">Biblijske aplikacije</h3>
<p><strong>Kršćanska sadašnjost</strong> nudi <strong>HR Biblija</strong> s mjerodavnim hrvatskim prijevodom. Dodatne opcije uključuju <em>Katolička Biblija</em> (s pretvaranjem teksta u govor), <em>Biblijska tražilica</em> (offline pretraživač usklađen s vatikanskim smjernicama iz 2008.) i <em>Knjiga O Kristu</em> od Biblice (hrvatsko-engleski paralelni prikaz).</p>
</section>
<section id="molitvene-i-duhovne-aplikacije" class="level3">
<h3 class="anchored" data-anchor-id="molitvene-i-duhovne-aplikacije">Molitvene i duhovne aplikacije</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Aplikacija</th>
<th>Sadržaj</th>
<th>Preuzimanja</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nova Eva</td>
<td>Misna čitanja, brevijar, propovijedi</td>
<td>5.000+</td>
</tr>
<tr class="even">
<td>Krunica</td>
<td>Tajne dana, vodič</td>
<td>1.000+</td>
</tr>
<tr class="odd">
<td>Katolički molitvenik</td>
<td>100+ molitava</td>
<td>5.000+</td>
</tr>
<tr class="even">
<td>Biblija365</td>
<td>Videi The Bible Project</td>
<td>1.000+</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
</section>
<section id="viii.-dio-utjecaj-digitalne-transformacije" class="level1">
<h1>VIII. DIO: UTJECAJ DIGITALNE TRANSFORMACIJE</h1>
<section id="covid-19-kao-katalizator" class="level2">
<h2 class="anchored" data-anchor-id="covid-19-kao-katalizator">COVID-19 kao katalizator</h2>
<p>Pandemija COVID-19 označila je <strong>prekretnicu u digitalnoj transformaciji</strong> katoličkih medija u Hrvatskoj. Prije 2020., online prijenos mise bio je rijetka iznimka. Nakon pandemije, postao je standardna praksa u većini župnih zajednica.</p>
<section id="online-prijenosi-misa" class="level3">
<h3 class="anchored" data-anchor-id="online-prijenosi-misa">Online prijenosi misa</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 28%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Izvor</th>
<th>Format</th>
<th>Jezik/Doseg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Međugorje</td>
<td>Svakodnevno</td>
<td>10 jezika (HR, DE, EN, IT, ES, FR, PL, SK, RU, AR)</td>
</tr>
<tr class="even">
<td>HKS</td>
<td>12:00 dnevno</td>
<td>Hrvatski</td>
</tr>
<tr class="odd">
<td>HRT</td>
<td>Nedjeljom 10:00</td>
<td>Nacionalno</td>
</tr>
<tr class="even">
<td>Laudato TV</td>
<td>7:00 i 10:30</td>
<td>Nacionalno</td>
</tr>
<tr class="odd">
<td>HKR</td>
<td>7:00 dnevno</td>
<td>Radio + streaming</td>
</tr>
<tr class="even">
<td>Biskupije</td>
<td>Varijabilno</td>
<td>Lokalno</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="transformacija-tiskanih-medija" class="level2">
<h2 class="anchored" data-anchor-id="transformacija-tiskanih-medija">Transformacija tiskanih medija</h2>
<section id="glas-koncila" class="level3">
<h3 class="anchored" data-anchor-id="glas-koncila">Glas Koncila</h3>
<p>Naklada je pala s ~140.000 (1970-e) na procijenjenih ~15.000 (2025.), reflektirajući globalni trend pada tiskanih medija.</p>
<p><strong>Glas Koncila</strong>, vodeći katolički tjednik, razvio je digitalni model:</p>
<ul>
<li><strong>Print:</strong> Kontinuirano od 1962.</li>
<li><strong>Digitalna pretplata:</strong> 55 EUR godišnje</li>
<li><strong>PDF arhiv:</strong> 53+ stranica tjedno</li>
<li><strong>Web:</strong> glas-koncila.hr s vijestima</li>
</ul>
</section>
</section>
<section id="digitalne-platforme-za-župno-poslovanje" class="level2">
<h2 class="anchored" data-anchor-id="digitalne-platforme-za-župno-poslovanje">Digitalne platforme za župno poslovanje</h2>
<section id="e-župe-sustav" class="level3">
<h3 class="anchored" data-anchor-id="e-župe-sustav">E-župe sustav</h3>
<p><strong>E-župe</strong> (e-zupe.com) digitalizira župno poslovanje:</p>
<ul>
<li><strong>Prijave sakramenata:</strong> Krštenje, pričest, krizma, vjenčanje</li>
<li><strong>Katekumeni:</strong> Online prijave</li>
<li><strong>Blagoslov obitelji:</strong> QR kod sustav</li>
<li><strong>Zaručnički tečajevi:</strong> Online komponente</li>
<li><strong>Donacije:</strong> Župne uplate</li>
<li><strong>GDPR:</strong> Potpuna usklađenost</li>
</ul>
</section>
<section id="virtualna-hodočašća" class="level3">
<h3 class="anchored" data-anchor-id="virtualna-hodočašća">Virtualna hodočašća</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Svetište</th>
<th>Platforma</th>
<th>Format</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Marija Bistrica</td>
<td>HeritageCroatia.com</td>
<td>360° interaktivna šetnja</td>
</tr>
<tr class="even">
<td>Trsat</td>
<td>HeritageCroatia.com</td>
<td>50 panorama</td>
</tr>
<tr class="odd">
<td>Gospa Sinjska</td>
<td>Google Play app</td>
<td>Mobilna aplikacija</td>
</tr>
<tr class="even">
<td>Međugorje</td>
<td>medjugorje.hr</td>
<td>Live streaming</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
</section>
<section id="ix.-dio-ključni-akteri" class="level1">
<h1>IX. DIO: KLJUČNI AKTERI</h1>
<section id="institucionalni-akteri" class="level2">
<h2 class="anchored" data-anchor-id="institucionalni-akteri">Institucionalni akteri</h2>
<p><strong>Hrvatska biskupska konferencija</strong> nadzire katoličke medije kroz nekoliko tijela:</p>
<ul>
<li><strong>Povjerenstvo za društvene komunikacije</strong> (predsjeda pomoćni biskup Mijo Gorski): uspostavlja medijske politike</li>
<li><strong>Tiskovni ured HBK-a</strong> (glasnogovornik Zvonimir Ancić): službene komunikacije i odnosi s medijima</li>
<li><strong>IKA</strong> (gl. urednik dr. Siniša Kovačić, v.d. ravnatelj vlč. Enco Rodinis): ~50 vijesti dnevno, 40+ novinara</li>
</ul>
<p><strong>Hrvatsko društvo katoličkih novinara (HDKN)</strong>, koje predsjeda dr. Suzana Peran, provodi godišnje nagrade za Svjetski dan društvenih komunikacija i surađuje na projektu provjere činjenica <strong>KAT</strong> s Hrvatskim katoličkim sveučilištem i HKR-om, financiranom od EU.</p>
</section>
<section id="individualni-akteri-svećenici-na-društvenim-mrežama" class="level2">
<h2 class="anchored" data-anchor-id="individualni-akteri-svećenici-na-društvenim-mrežama">Individualni akteri — svećenici na društvenim mrežama</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Svećenik</th>
<th>Platforma</th>
<th>Pratitelji</th>
<th>Stil sadržaja</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Don Tomislav Lukač</td>
<td>TikTok</td>
<td><strong>68.000+</strong></td>
<td>Kratki video formati, pop kultura</td>
</tr>
<tr class="even">
<td>Don Damir Stojić</td>
<td>Facebook/Instagram</td>
<td><strong>52.800 FB / 32.000+ IG</strong></td>
<td>Kateheza, aktualni događaji</td>
</tr>
<tr class="odd">
<td>Fra Ivan D. Iličić</td>
<td>Facebook</td>
<td>~14.040</td>
<td>Motivacijski sadržaj</td>
</tr>
<tr class="even">
<td>Pater Ivan Ike Mandurić</td>
<td>Facebook</td>
<td>~4.840</td>
<td>Politički/društveni komentar</td>
</tr>
<tr class="odd">
<td>Fra Ivo Pavić</td>
<td>—</td>
<td>—</td>
<td>Karizmatske obnove (80-120.000 hodočasnika/god)</td>
</tr>
</tbody>
</table>
<p><strong>Don Damir Stojić</strong>, salezijanski svećenik rođen u Kanadi s hercegovačkim podrijetlom, služio je kao studentski kapelan na Jarunu (2007.-2020.) prije nego što je postao župnik (2020.-2023.). Sada služi kao vojni kapelan na Hrvatskom vojnom učilištu. Ima najveći broj pratitelja među hrvatskim svećenicima.</p>
<p><strong>Pater Ike Mandurić</strong>, isusovac zaređen u dobi od 47 godina nakon studija arhitekture i vojne službe, vodi molitvenu zajednicu <em>Srce Isusovo</em> u Bazilici Srca Isusova u Zagrebu. Njegov Facebook profil višestruko je suspendiran zbog kontroverznih objava.</p>
</section>
<section id="laički-influenceri" class="level2">
<h2 class="anchored" data-anchor-id="laički-influenceri">Laički influenceri</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Osoba/Profil</th>
<th>Platforma</th>
<th>Pratitelji</th>
<th>Fokus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ChanceForWalk</td>
<td>Instagram</td>
<td>~9.820</td>
<td>Prve katoličke influencerice</td>
</tr>
<tr class="even">
<td>Marin Miletić</td>
<td>YouTube</td>
<td>~5.250</td>
<td>Vjeroučitelj, edukacija</td>
</tr>
<tr class="odd">
<td>Bitno.net</td>
<td>Multi</td>
<td>48.000 IG</td>
<td>Portal, podcasti</td>
</tr>
</tbody>
</table>
</section>
<section id="laičke-zajednice-i-pokreti" class="level2">
<h2 class="anchored" data-anchor-id="laičke-zajednice-i-pokreti">Laičke zajednice i pokreti</h2>
<p><strong>Božja pobjeda</strong>, katolička karizmatska zajednica osnovana 2007. u Zagrebu, održava preko 37.000 Instagram pratitelja i proizvodi BP Podcast. Ključne figure uključuju gitarista Petra Buljana (dobitnik Porina), tekstopisce Romanu Bilaver i basista Grgura Sesara. Zajednica se okuplja četvrtkom u crkvi Sveta Mati Slobode na Jarunu.</p>
<ul>
<li><strong>Koncert 2022:</strong> ~50.000 ljudi na stadionu Maksimir</li>
<li><strong>Albumi:</strong> Tri studijska izdanja</li>
<li><strong>Nominacija:</strong> Porin</li>
</ul>
<p><strong>Muževni budite</strong>, osnovan 2019. kao prvi hrvatski portal za katoličke muškarce, narastao je na preko 9.260 Instagram pratitelja. Aktivnosti uključuju mjesečne javne molitve krunice u više gradova i godišnje konferencije <em>Budi muškarac</em>.</p>
</section>
<section id="katolička-glazbena-scena" class="level2">
<h2 class="anchored" data-anchor-id="katolička-glazbena-scena">Katolička glazbena scena</h2>
<ul>
<li><strong>Alan Hržica</strong> (~29.000 IG): Voditelj molitvene zajednice <em>Srce Isusovo</em>, dobitnik Porina za <em>Kamenita vrata live</em> (2016.)</li>
<li><strong>Ivana Husar Mlinac i Marija Husar Rimac</strong> (sestre Husar): Vodeći ženski glasovi hrvatske duhovne glazbe</li>
<li><strong>Vanessa Mioč</strong>: Pjevačica u usponu pod mentorstvom Alana Hržice</li>
</ul>
<hr>
</section>
</section>
<section id="x.-dio-financiranje-i-održivost" class="level1">
<h1>X. DIO: FINANCIRANJE I ODRŽIVOST</h1>
<section id="strukturni-izazovi" class="level2">
<h2 class="anchored" data-anchor-id="strukturni-izazovi">Strukturni izazovi</h2>
<ul>
<li><strong>Pad tiraže</strong>: Naklada dnevnih novina pala s 640.000 (2008.) na ~300.000 (2013.), s godišnjim padovima od 14-15%</li>
<li><strong>Digitalna transformacija</strong>: Samo 9% Hrvata plaća za online vijesti</li>
<li><strong>Demografski trendovi</strong>: Emigracija mlade radne populacije</li>
<li><strong>Ovisnost o državnom financiranju</strong>: Podložnost političkim fluktuacijama</li>
<li><strong>Fragmentacija</strong>: Mnogo malih platformi umjesto integriranih rješenja</li>
</ul>
</section>
<section id="prednost-povjerenja" class="level2">
<h2 class="anchored" data-anchor-id="prednost-povjerenja">Prednost povjerenja</h2>
<p>Katolički mediji profitiraju od značajne institucionalne prednosti povjerenja. Istraživanja pokazuju da Hrvati vjeruju Katoličkoj crkvi (<strong>3,44 od 5</strong>) više nego bilo kojoj drugoj instituciji, u usporedbi s povjerenjem u domaće medije (2,78/5) i novinare (2,73/5). Opće povjerenje u vijesti u Hrvatskoj palo je s 45% (2021.) na samo <strong>32% (2024.)</strong>, sugerirajući da institucionalna vjerodostojnost katoličkih medija može postati sve vrednija.</p>
<hr>
</section>
<section id="zaključak" class="level2">
<h2 class="anchored" data-anchor-id="zaključak">Zaključak</h2>
<p>Hrvatski katolički medijski ekosustav ulazi u 2026. godinu na raskrižju. Njegovi povijesni temelji, izgrađeni kroz otpor komunističkoj eri i održani snažnim nacionalnim katoličkim identitetom, pružaju institucionalnu dubinu neuobičajenu za religijske medije. Konsolidacija 2018. u HKM predstavlja strateško prepoznavanje da je jedinstvena digitalna prisutnost neophodna za opstanak. Uspjeh Laudato TV-a kao najgledanije lokalne televizije u Hrvatskoj demonstrira apetit publike za sadržaj temeljen na vrijednostima.</p>
<section id="ključni-nalazi" class="level3">
<h3 class="anchored" data-anchor-id="ključni-nalazi">Ključni nalazi</h3>
<ol type="1">
<li><strong>173 godine tradicije</strong> — Od Katoličkog lista (1849.) do HKM (2018.)</li>
<li><strong>Pionirski duh Riječke nadbiskupije</strong> — prva na društvenim mrežama</li>
<li><strong>Akademska izvrsnost</strong> — Bogoslovska smotra u Web of Science</li>
<li><strong>Uspješni modeli</strong> — Laudato TV, Nova Eva, Bitno.net</li>
<li><strong>Dijaspora povezana</strong> — 189 misija s digitalnom infrastrukturom</li>
<li><strong>COVID-19 ubrzanje</strong> — Online mise postale standard</li>
</ol>
</section>
<section id="strateški-nedostaci" class="level3">
<h3 class="anchored" data-anchor-id="strateški-nedostaci">Strateški nedostaci</h3>
<ol type="1">
<li><strong>TikTok prostor ostaje neiskorišten</strong> unatoč proof-of-concept uspjehu don Tomislava Lukača s 68.000 pratitelja</li>
<li><strong>Namjenska podcast kultura je nerazvijena</strong> u usporedbi s anglofonim katoličkim svijetom</li>
<li><strong>Infrastruktura mobilnih aplikacija zaostaje</strong> za potencijalom</li>
<li><strong>Institucionalni deficit na Instagramu</strong> — biskupije značajno zaostaju za medijskim brendovima</li>
</ol>
<hr>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Kako citirati
</div>
</div>
<div class="callout-body-container callout-body">
<p>Šikić, L. et al.&nbsp;(2026). Hrvatski katolički digitalni medijski ekosustav: Sveobuhvatna strukturalna analiza. U: <em>Prikaz i analiza katoličke tematike u digitalnom medijskom prostoru</em>. Hrvatsko katoličko sveučilište. Dostupno na: <a href="https://github.com/lusiki/DigiKat">github.com/lusiki/DigiKat</a></p>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/lusiki\.github\.io\/DigiKat\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>