#!/usr/bin/env Rscript
# =============================================================================
# R/05_codebook.R
# Auto-generate CODEBOOK.md from the official corpus (or the sample) schema: every
# variable with type, % missing, and example values / levels, grouped heuristically.
#
# Documents data/digikat_corpus.rds, which is what the site publishes. That is the accumulator's
# schema plus the dk_* provenance columns the inclusion rule adds. --accumulator documents
# data/merged_comprehensive.rds instead.
#
# Run where the data lives:  Rscript R/05_codebook.R [--sample] [--accumulator]
# =============================================================================
suppressPackageStartupMessages({ library(here) })
source(here::here("R/lib/digikat_paths.R"), encoding = "UTF-8")
args       <- commandArgs(trailingOnly = TRUE)
use_sample <- "--sample" %in% args
path <- here::here(
  if (use_sample) "data/sample/merged_sample.rds"
  else if ("--accumulator" %in% args) digikat_legacy_master_path()
  else digikat_corpus_path()
)
if (!file.exists(path))
  stop("Not found: ", path, if (!use_sample) "\nRun on the pipeline machine, or use --sample." else "")

d   <- as.data.frame(readRDS(path))
out <- here::here("CODEBOOK.md")

classify <- function(name) {
  n <- tolower(name)
  if (grepl("date|year|month|day|time", n))                                   return("Temporal")
  if (grepl("text|title|desc|body|content|url|link", n))                       return("Content")
  if (grepl("platform|source|domain|channel|page|author|account|outlet", n))  return("Source")
  if (grepl("term|topic|theme|categ|match|tag|label", n))                      return("Categorization")
  if (grepl("like|view|share|comment|react|love|haha|wow|sad|angry|reach|engag", n)) return("Engagement")
  if (grepl("sent|emo|tone|polar|crosentilex|lila|conflict|joy|fear|trust|anger|disgust", n)) return("Sentiment/Emotion")
  "Other"
}
example <- function(col) tryCatch({
  nonmissing <- col[!is.na(col)]
  if (!length(nonmissing)) return("(all values missing)")
  if (is.numeric(col)) {
    return(sprintf(
      "range %s-%s",
      signif(min(nonmissing), 3),
      signif(max(nonmissing), 3)
    ))
  }
  u <- unique(nonmissing)
  if (length(u) <= 6) paste(utils::head(u, 6), collapse = "; ") else paste0(length(u), " distinct")
}, error = function(e) "")

cb <- do.call(rbind, lapply(names(d), function(nm) data.frame(
  group = classify(nm), variable = nm, type = paste(class(d[[nm]]), collapse = "/"),
  missing_pct = round(100 * mean(is.na(d[[nm]])), 1),
  example = substr(as.character(example(d[[nm]])), 1, 80), stringsAsFactors = FALSE)))

con <- file(out, open = "w", encoding = "UTF-8")
writeLines(c(
  "# Codebook — DigiKat",
  paste0("> Auto-generated by `R/05_codebook.R` on ", format(Sys.time(), tz = "UTC"), " UTC from ",
         if (use_sample) "`data/sample/merged_sample.rds` (SAMPLE)" else "the master corpus", ". Do not hand-edit."),
  paste0("Variables: ", nrow(cb)), ""), con)
for (g in c("Temporal", "Content", "Source", "Categorization", "Engagement", "Sentiment/Emotion", "Other")) {
  sub <- cb[cb$group == g, , drop = FALSE]
  if (!nrow(sub)) next
  writeLines(c(paste0("## ", g, " (", nrow(sub), ")"), "",
               "| Variable | Type | % missing | Example / levels |", "|---|---|---|---|"), con)
  for (i in seq_len(nrow(sub)))
    writeLines(sprintf("| `%s` | %s | %s | %s |", sub$variable[i], sub$type[i], sub$missing_pct[i],
                       gsub("\\|", "\\\\|", sub$example[i])), con)
  writeLines("", con)
}
close(con)
cat("Wrote", out, "—", nrow(cb), "variables.\n")
