#!/usr/bin/env Rscript
# Capture the current computational environment without mutating dependencies.
#
# Usage:
#   Rscript R/capture_environment.R
#   Rscript R/capture_environment.R --output=ENVIRONMENT.md
#
# Dependency snapshotting is intentionally separate; use
# R/snapshot_dependencies.R when dependency state should change.

source("R/lib/digikat_utils.R", encoding = "UTF-8")

args <- commandArgs(trailingOnly = TRUE)
if ("--help" %in% args) {
  cat("Usage: Rscript R/capture_environment.R [--output=PATH]\n")
  quit(save = "no", status = 0L)
}

output <- digikat_cli_value(args, "--output", "ENVIRONMENT.md")
model_path <- "resources/models/croatian-set-ud-2.5-191206.udpipe"
pinned_model_sha <- "b8e0ad212bdc84c57366bd7267d21810e1fd3239c4d22ca5867f94e76c6cedc7"

quarto_candidates <- c(
  Sys.getenv("QUARTO_PATH", unset = ""),
  Sys.which("quarto"),
  "C:/Program Files/Quarto/bin/quarto.exe"
)
quarto_candidates <- unique(quarto_candidates[nzchar(quarto_candidates)])
quarto_path <- quarto_candidates[file.exists(quarto_candidates)][1L] %||% ""
quarto_version <- if (nzchar(quarto_path)) {
  tryCatch(
    paste(system2(quarto_path, "--version", stdout = TRUE, stderr = TRUE), collapse = " "),
    error = function(error) paste("unavailable:", conditionMessage(error))
  )
} else {
  "not found"
}

dependencies <- if (requireNamespace("renv", quietly = TRUE)) {
  tryCatch(
    renv::dependencies(".", progress = FALSE, errors = "ignored"),
    error = function(error) NULL
  )
} else {
  NULL
}
dependency_names <- if (is.null(dependencies)) character() else sort(unique(dependencies$Package))
installed <- rownames(installed.packages())
missing <- setdiff(dependency_names, installed)
present <- setdiff(dependency_names, missing)

model_metadata <- if (file.exists(model_path)) {
  digikat_file_metadata(model_path, include_hash = TRUE)
} else {
  list(path = model_path, bytes = NA, modified_utc = NA, sha256 = NA)
}
model_status <- if (identical(model_metadata$sha256, pinned_model_sha)) {
  "matches the pinned SHA-256"
} else {
  "DOES NOT match the pinned SHA-256"
}

session <- sessionInfo()
lock_status <- if (file.exists("renv.lock")) {
  paste0("present (`", digikat_hash_file("renv.lock"), "`)")
} else {
  "missing"
}

lines <- c(
  "# Environment snapshot — DigiKat",
  "",
  "> Generated by `R/capture_environment.R`. This report is read-only; it does not install packages or update `renv.lock`.",
  "",
  paste0("- Generated: ", format(Sys.time(), tz = "UTC", usetz = TRUE)),
  paste0("- R: ", R.version.string),
  paste0("- Platform: ", R.version$platform),
  paste0("- Locale (`LC_CTYPE`): ", Sys.getlocale("LC_CTYPE")),
  paste0("- Native Windows UTF-8 assumption satisfied (R >= 4.2): ", getRversion() >= "4.2.0"),
  paste0("- Quarto: ", quarto_version),
  paste0("- Quarto executable: ", if (nzchar(quarto_path)) paste0("`", quarto_path, "`") else "not found"),
  paste0("- `renv.lock`: ", lock_status),
  "",
  "## Pinned language model",
  "",
  paste0("- File: `", model_path, "`"),
  paste0("- Bytes: ", model_metadata$bytes),
  paste0("- SHA-256: `", model_metadata$sha256, "`"),
  paste0("- Verification: **", model_status, "**"),
  "",
  "## Discovered R dependencies",
  "",
  paste0("- Referenced packages: ", length(dependency_names)),
  paste0("- Installed: ", length(present)),
  paste0("- Missing: ", length(missing)),
  "",
  if (length(missing)) paste0("Missing packages: `", paste(missing, collapse = "`, `"), "`.") else "No discovered package is missing.",
  "",
  "## Session information",
  "",
  "```text",
  capture.output(print(session)),
  "```",
  ""
)
lines <- sub("[ \t]+$", "", lines)

dir.create(dirname(output), recursive = TRUE, showWarnings = FALSE)
connection <- file(output, open = "wb")
writeLines(enc2utf8(lines), connection, useBytes = TRUE)
close(connection)
cat("Wrote environment report:", output, "\n")
if (length(missing)) {
  cat("Missing discovered packages:", paste(missing, collapse = ", "), "\n")
}
